aws/aws-k8s-tester

internal/eks/worker_node_log.go

Changed the fetchWorkerNodeLogs function to work with concurrency using goroutines and channels. The goroutines are limited by a buffered channel of 200 for now to avoid an error regarding too many open files. But we can reevaluate that number if necessary.

Add concurrency to log fetcher

---

CHANGELOG-0.1.md

Updating change log md file with pull request #10

Update ChangeLog with pr10

---

CHANGELOG-0.1.md
ekstester/tester.go
go.mod
go.sum
internal/eks/tester_embedded.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/s3/api.go
vendor/modules.txt

Add `GetKubectlVersion` to satisfy kubetest deployer interface.
ref. https://github.com/kubernetes/test-infra/pull/10216#issuecomment-441748304

ekstester: add "GetKubectlVersion" 

---

CHANGELOG-0.1.md
README.md

None
- Added 0.1.7 to CHANGELOG
- Use a variable for os in local testing command in README
- Fixed typo in README

Update CHANGELOG for 0.1.7 and README

---

CHANGELOG-0.1.md

PR #21 
Adding PR 21 to CHANGELOG

Add pr 21 to CHANGELOG

---

ec2config/config.go
ec2config/config_test.go
internal/ec2/s3.go
internal/eks/s3/plugin_embedded.go

Adding lifecycle rule to buckets in ec2 package and ec2 config

Add lifecycle rule to S3 buckets in EC2

---

eksconfig/config.go

Change default node instance type

---

eksconfig/config.go

Remove AMI check; let EKS take care

---

eksconfig/config.go
eksconfig/config_test.go

#45
* Protect from nil `cfg.ALBIngressController`

Remove ALB config

---

e2e/framework/resource/daemonset.go
e2e/framework/resource/deployment.go
e2e/resources/resources.go

N/A
Fixed a pointer and wrong type issue.
Added long wait periods for daemonsets to be ready.

Update framework daemonset and deployment resources

---

e2e/utils/utils.go

N/A
Added code to add annotations to daemonsets.
e.g. 
```
annotations := map[string]string{
"prometheus.io/scrape": "true",
"prometheus.io/port":   "61678",
}
```
`utils.AddAnnotationsToDaemonSet(ctx, f, ns, ds, annotations)`
Adds annotations such as:
```
spec:
revisionHistoryLimit: 10
selector:
matchLabels:
k8s-app: aws-node
template:
metadata:
annotations:
**prometheus.io/port: "61678"**
**prometheus.io/scrape: "true"**
```

Add code to add annotations to a daemonset

---

e2e/tester/framework.go

Update to use rand seed. So that the generated random number if randomized in parallel test run. 
@gyuho 

Update to use randon seed source

---

e2e/tester/pkg/cluster.go
e2e/tester/pkg/config.go
e2e/tester/pkg/eksctl.go

Add support for creating EKS cluster

Add support for creating EKS cluster

---

eks/eks.go

Wait for before trying to delete the k8s namespace on cluster down and
when MNG and the ALB/NLB testers have been run.
Because we asked Kubernetes to delete the NLB hello world and ALB2048
Deployment/Service above, and both of these interact with the underlying
Kubernetes AWS cloud provider to clean up the cloud load balancer
backing the Service of type LoadBalancer. The calls to delete the
Service return immediately (successfully) but the cloud load balancer
resources may not have been deleted yet, including the ENIs that were
associated with the cloud load balancer. When, later, aws-k8s-tester
tries deleting the VPC associated with the test cluster, it will run
into permissions issues because the IAM role that created the ENIs
associated with the ENIs in subnets associated with the …

wait before attempting to delete k8s namespace

---

eks/mng/nodes.go
eks/ng/nodes.go

Prefixes ASG Stack names with EKSConfig.Name to avoid collisions on reruns

---

Makefile

Added make commands for s3 and docker push

---

CHANGELOG/CHANGELOG-1.4.md
Makefile
eks/cron-jobs/cron-jobs.go
eks/eks.go
eks/jobs-echo/jobs-echo.go
eksconfig/README.md
eksconfig/add-on-cron-jobs.go
eksconfig/add-on-jobs-echo.go
eksconfig/config.go
eksconfig/default.yaml
eksconfig/env.go
eksconfig/env_test.go

In case dockerhub has outages, use ECR as fallback.

*: allow custom busybox repository from ECR

---

Dockerfile
Makefile
hack/build.sh
hack/ec2config.gen.sh
hack/eksconfig.gen.sh
hack/fmt.sh
hack/install.sh
hack/unit.sh
hack/updatedep.sh

Following https://github.com/kubernetes/kubernetes/tree/master/hack

Renamed scripts to hack for parity with k/k style

---

eksconfig/overprovisioning.go

Fixed a bug where resources werent correctly defaulted in Overprovisioning

---

eks/clusterautoscaler/clusterautoscaler.go
eksconfig/overprovisioning.go

Fixed a bug with clusterautoscaler maxnodes

---

eksconfig/config.go

Fail if YAML fields not recognized

---

eks/clusterautoscaler/clusterautoscaler.go
eks/clusterautoscaler/clusterautoscaler.gotmpl
eks/hollow-nodes/remote/hollow-nodes.go

Fixed a bug where hollow nodes didn't correctly delete pods or nodes

---

images/kubemark/Dockerfile

Added a dockerfile for building OSS kubemark

---

.gitignore
eks/clusterautoscaler/clusterautoscaler.go
eks/clusterautoscaler/clusterautoscaler.gotmpl
eksconfig/clusterautoscaler.go

Made it so that you can specify resource limits for the CA, and added defaults.

Cluster Autoscaler AKT defaults

---

Makefile
eks/cluster-loader/clusterloader2/addon.go
eks/cluster-loader/clusterloader2/cluster-loader.gotmpl
eks/cluster-loader/configs/cluster-autoscaler/config.yaml
eks/eks.go
eksconfig/cluster-loader.go
eksconfig/spec.go
eksconfig/status.go
images/clusterloader2/Dockerfile

Added add-on options with AKT for CL2 as a pod. 
Fixed some minor config changes.

Enabled AKT Automation of CL2 Tests with Addon

---

eks/cluster-loader/clusterloader2/addon.go
eks/cluster-loader/clusterloader2/cluster-loader.gotmpl
eksconfig/cluster-loader.go

Added S3 Support for CL2 Tests

---

eks/cluster-loader/configs/cluster-autoscaler/config.yaml

Fixes some logical issues with the CA + CL2 test configurations

---

eks/cluster-loader/configs/cluster-autoscaler/config.yaml

Added warning message for configuration file, and fixed a minor bug

---

eks/cluster-loader/clusterloader2/addon.go

Added job wait for succeed for CL2 Add-on to finish

---

eksconfig/cluster-loader.go

Added defaults for CL2 add-on

---

eks/cluster-loader/clusterloader2/addon.go

Timeout error handling for CL2 large tests

---

CHANGELOG/CHANGELOG-1.5.md
eks/eks.go
eksconfig/add-on-cluster-loader-local.go
eksconfig/add-on-cluster-loader-remote.go
eksconfig/config.go

*: release v1.5.1

---

eks/clusterautoscaler/clusterautoscaler.go

Was previously segfaulting if you didn't enable both MNG and ASG. Made it check for nil so it doesn't segfault.

Fixed logic for MNG and ASG requirements for CA

---

eks/cluster-loader/clusterloader2/addon.go
eks/cluster-loader/clusterloader2/cluster-loader.gotmpl
eksconfig/cluster-loader.go
eksconfig/config.go
eksconfig/default.yaml

added option to specify nodeSelectorTerms for Cl2 job pod to schedule on

---

CHANGELOG/CHANGELOG-1.5.md
go.mod
go.sum
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/s3/api.go
vendor/github.com/aws/aws-sdk-go/service/ssm/api.go
vendor/modules.txt

CHANGELOG: update, bump up aws sdk, go version

---

CHANGELOG/CHANGELOG-1.5.md
eks/cluster/vpc.go
go.mod
go.sum
vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/github.com/aws/aws-sdk-go/service/ssm/api.go
vendor/modules.txt

```
DELETE_FAILED
The vpc vpc-028d8568a626d6052 currently has a subnet within CIDR block 10.2.0.0/16 (Service: AmazonEC2; Status Code: 400; Error Code: InvalidCidrBlock.InUse; Request ID: 61cfbfa2-e53b-406d-81ed-3b216cd01a99; Proxy: null)
```

*: update SDK dependency, fix VPC deletes

---

eks/ng/autoscaler/cluster-autoscaler.go

Added image url for CA for nodegroups

---

pkg/aws/s3/s3.go

Setting `LocationConstraint` to `us-east-1` when creating a S3 bucket causes `InvalidLocationConstraint`.
This region seems to be handled differently and this param should not be passed in. The location will default to us-east-1.
Reference: https://github.com/boto/boto3/issues/125

Do not set LocationConstraint when creating a S3 bucket in us-east-1

---

eksconfig/add-on-node-groups.go

Adds support for EC2 service principals in isolated regions

(eksconfig): update valid ec2 service principals

---

eks/cluster/cluster.go

eks/cluster: do not delete other resources on cluster delete failures

---

CHANGELOG/CHANGELOG-1.5.md
ec2config/config.go
ec2config/validate-defaults.go
eks/ng/nodes.go
eks/ng/nodes_test.go
eksconfig/add-on-node-groups.go
go.mod
go.sum
vendor/github.com/aws/aws-sdk-go/aws/version.go
vendor/modules.txt

*: prefer SSM param over AMI ID, do not include "SSM:Parameter" in CFN

---

eks/conformance/conformance.go
eksconfig/add-on-conformance.go

Sorry for being sloppy on the last change.

conformance: fix e2e-repo-config flag. Set SonobuoyE2eRepoConfig default

---

hack/build.sh

hack/build.sh: fix GOARCH set

---

CHANGELOG/CHANGELOG-1.5.md
eksconfig/README.md
eksconfig/env.go

eksconfig: fix "AddOnAmiSoftLockupIssue454" env parsing

---

CHANGELOG/CHANGELOG-1.5.md
cmd/aws-k8s-tester/eks/create-stresser-v2.go

Updated changelog for #206 
@gyuho

CHANGELOG: update v1.5.9 with #206

---

k8s-tester/csi-ebs/cmd/k8s-tester-csi-ebs/main.go
k8s-tester/csi-ebs/fixtures.go
k8s-tester/csi-ebs/go.mod
k8s-tester/csi-ebs/tester.go

Signed-off-by: jonahjon <jonahjones094@gmail.com>
Adding tests for provision/resizing to EBS CSI Driver.

Updaitng ebs-csi test functionality

---

CHANGELOG/CHANGELOG-1.6.md

CHANGELOG: update

---

eks/eks.go
eks/gpu/gpu.go

gpu test is out-of-dated
update MPI deployment yaml, and add mpi job test

update gpu test

---

eks/eks.go
eks/gpu/gpu.go
eks/neuron/neuron.go

add neuron test

---

eks/eks.go
eks/trainium/trainium.go

Add trainium test

---

Dockerfile
Makefile
eksconfig/add-on-conformance.go

bake sonobuoy binary to tester image

Bake sonobuoy binary to tester image

---

eks/cni-vpc/cni-vpc.go

See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

stop using beta.kubernetes.io/os and arch

---

Makefile

Updates the GO_VERSION for Docker builds to align with go.mod

Update GO_VERSION for Docker builds

---

go.work

Add go.work

---

kubetest2/README.md

Adds a README for the `kubetest` package covering the `eksctl `deployer.

Add README for kubetest2 package

---

kubetest2/Makefile
kubetest2/internal/deployer/eksapi/deployer.go
kubetest2/internal/deployer/eksctl/deployer.go
kubetest2/internal/version.go

Moves to a central version var.

Fix version variables

---

Dockerfile.kubetest2
e2e2/internal/framework_extensions/client.go
e2e2/test/cases/nvidia/main_test.go
e2e2/test/cases/nvidia/mpi_test.go

Embeds the manifest files used for tests in the compiled binaries.

Embed manifests in test binariees

---

kubetest2/internal/deployers/eksapi/cloudformation/infra.yaml

Fix partition in VPC CNI IPv6 inline policy

---

e2e2/test/cases/nvidia/main_test.go
e2e2/test/cases/nvidia/mpi_test.go

Tag should be `go:embed` not `go+embed` 🤦 

Use correct embed tags for nvidia cases

---

kubetest2/internal/deployers/eksapi/cluster.go

Logs the cluster details after creation, to aid debugging.

Log cluster details after creation

---

kubetest2/internal/deployers/eksapi/infra.go

Leaked ENI's may not have reached the `available` status when the cleanup is done, and left-behind ENI's will block VPC deletion. This is more likely to happen when the `--unmanaged-nodes` option is used, or with partitions other than `aws`. This PR adds a waiter for the `available` status on all ENI's in the VPC before deleting them.

Improve leaked ENI cleanup

---

kubetest2/internal/deployers/eksapi/deployer.go

Add m6i.xlarge to default instance types

---

Dockerfile.kubetest2

* Build binary for newly added e2e test which will be used to compare all resrouces limit using ulimit to make sure the resource limits is unchanged.
* Newly added ulimit test PR: https://github.com/aws/aws-k8s-tester/pull/420

add ulimit test in Dockerfile.kubetest2

---

Dockerfile.kubetest2

Add inference test e2e go binary to Dockerfile.kubetest2

---

e2e2/test/images/nvidia/Dockerfile

fix codebuild

---

e2e2/test/cases/nvidia/manifests/mpi-job-nccl-test-multi-node.yaml
e2e2/test/images/nvidia/Dockerfile

EFA installation was updated with MPI5 in #487 for nvidia, adjust config for it

Config MPI5 for EFA

---

kubetest2/internal/deployers/eksapi/k8s.go

This emits the node metrics multiple times, with different sets of dimensions, in order to make aggregation/dashboarding more reasonable.

Emit node metrics with multiple dimension sets

---

kubetest2/internal/deployers/eksapi/static_cluster.go

wait longer for node termination

---

kubetest2/internal/deployers/eksapi/templates/nvidia_static_cluster_nodepool.yaml.template

update consolidation policy

---

e2e2/test/cases/nvidia/manifests/efa-device-plugin.yaml
e2e2/test/cases/nvidia/mpi_test.go

Add new instance type, P5en, to EFA and RDMA supported instances.

chore(efa-device-plugin): Add P5en to EFA and RDMA supported instances

---

kubetest2/internal/deployers/eksapi/templates/nvidia_static_cluster_nodepool.yaml.template

bump up the emptiness wait

---

kubetest2/internal/deployers/eksapi/nodegroup.go
kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup.yaml.template

similar to #472, generalize the fix to non-efa use case

Bug(bottlerocket) fix volume mount for non-efa use case

---

kubetest2/internal/deployers/eksapi/templates/nvidia_static_cluster_nodepool.yaml.template

Increases the consolidation grace period to avoid interference while a test case runs.

Increase consolidation time to 10m

---

e2e2/test/cases/neuron/main_test.go

This update addresses a critical issue where MPIJob pods failed to launch due to incorrect resource requests (neuron, neuroncore, EFA). The root cause was local-scoped variables (`neuronPerNode`, `efaPerNode`, etc.) being used instead of updating the global state. As a result, the resource requests were set to 0, preventing pods from launching.
**Key Changes:**
1.  Corrected Scope of Capacity Variables
a. Switched from local variables to global variables (neuronPerNode, neuronCorePerNode, efaPerNode).
b.   Ensured global variables are updated directly within checkNodeTypes.
2. Updated Global State Management
a. `nodeCount` is now properly set at the global level to reflect the number of nodes.
b. Global capacity variables …

fix(e2e/nccom): Fix Global Capacity Variables to Correctly Populate MPIJob Resources

---

Dockerfile.kubetest2

This is used for some networking tests.

Add curl to kubetest2 container image

---

kubetest2/internal/deployers/eksapi/infra.go

bump up the deletion timeout

---

Config

Add build config

---

Makefile

Pin upstream kubetest2 version

---

test/cases/neuron-inference/bert_inference_test.go
test/cases/neuron-inference/main_test.go
test/cases/neuron-inference/vars.go

fix: add build tag to disable e2e tests from the normal unit test execution

---

test/cases/neuron-inference/bert_inference_test.go

Increases the timeouts for the neuron-inference tests

Increase neuron-inference-test timeouts

---

internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
internal/deployers/eksapi/templates/unmanaged-nodegroup.yaml.template

Minor change to require IMDSv2 for all instances launched using eksapi

Require IMDSv2 for eksapi launched instances

---

test/cases/nvidia/main_test.go

Intended to fix issues like
```
All nodes which are allocated for this job are already filled.
```
Which was occurring when num gpus was set as 0 because the device plugins weren't actually ready on the target nodes at test launch time. This fixes the ordering so that it waited for before any tests are attempted.

fix(nvidia/nccl): wait on plugins ready before collecting node info

---

internal/deployers/eksapi/node.go

fix: cease use of m4 instances

---

internal/deployers/eksapi/logs.go

When `--unmanaged-nodes` is used, we can easily get the list of instance IDs from the ASG API, which allows us to do log collection when no nodes are able to join the cluster (very helpful for debugging!)

feat(logs): discover instances from ASG if nodes do not join the cluster

---

internal/deployers/eksapi/logs.go

Adds some debug logging to log collection.

fix(logs): add debug logging

---

.github/workflows/ci.yaml
test/images/nvidia-inference/Dockerfile
test/images/nvidia-training/Dockerfile
test/images/nvidia/Dockerfile

updating NVIDIA test image Dockerfiles and versions of packages.
* standardize formatting and indentation
* make `/tmp` utilization uniform for build dependencies
* optimize ordering of dependencies (stable dependencies first -> application last)

chore: update nvidia deps

---

internal/deployers/eksapi/infra.go

* neuron test succeed but failed when clean up leaked ENI(s). It was waiting eni to be available and then delete them. But sometime the leaked eni might get auto deleted after instance fully terminated and the wait availble will failed because the enis have already gone.
```
2025-05-16T10:56:17.366Z
--- PASS: TestBertTraining (760.24s)
2025-05-16T10:56:17.366Z
--- PASS: TestBertTraining/bert-training (760.24s)
2025-05-16T10:56:17.366Z
--- PASS: TestBertTraining/bert-training/Neuron_training_Job_succeeds (760.24s)
2025-05-16T10:56:17.366Z
PASS
2025-05-16T10:56:17.500Z
2025/05/16 10:56:17 Successfully deleted Neuron device plugin and EFA device plugin manifests.
2025-05-16T10:56:17.500Z
2025/05/16 10:56:17 Tests finished with exit code 0
2025-05-16T10:56:17.505Z …
```

fix: gracefully handle ENIs already deleted during cleanup
