- CHANGELOG-0.1.md
- internal/eks/cluster_embedded.go
Upstream test failed:
```
W1108 01:33:52.498] {"level":"warn","ts":"2018-11-08T01:33:52.497Z","caller":"eks/tester_embedded.go:301","msg":"reverted Up","error":"'kubectl get all' output unexpected: No resources found.\n"}
W1108 01:33:52.498] failed to create cluster 'kubectl get all' output unexpected: No resources found.
```
> internal/eks: retries on "kubectl get all" 

- CHANGELOG-0.1.md
- internal/eks/tester_embedded.go
During cluster creation, there is now a channel listening for interruption or termination syscalls.  If a signal is received from that channel, the resources are cleaned up before exiting the process.  
> Handle Interrupt and Terminate Signals in Up

- internal/csi/csi.go
None
Changed command used to run test integration with kubernetes-sigs/aws-ebs-csi-driver 
> internal/csi: change testcmd for aws-ebs-csi-driver in csi.go

- internal/eks/s3/plugin_embedded.go
Adding lifecycle rule to S3 buckets to ensure that objects expire after specified number of days. 
> Add lifecycle to bucketForTests and bucketForAccessLogs

- eksconfig/config.go
- eksconfig/config_test.go
- internal/eks/worker_node_embedded.go
- internal/eks/worker_node_template.go
- internal/eks/worker_node_template_test.go
This should hopefully help fix most of the failures with the EKS [conformance](https://testgrid.k8s.io/sig-aws-eks-periodics#ci-kubernetes-e2e-aws-eks-1-11-conformance) and [correctness](https://testgrid.k8s.io/sig-aws-eks-periodics#ci-kubernetes-e2e-aws-eks-1-11-correctness) jobs.
The default aws recommendation is not to expose these ports for security reasons. But some conformance tests need these to pass.
/cc @gyuho
> Allow priviliged port access for worker node groups

- .gitignore
- internal/csi/csi.go
Fixing go mod checksum mismatch since EBS CSI is built using go 1.11.4. But the integration test instance is still using 1.11.3
Failed Prow Job link:
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-ebs-csi-driver/198/pull-aws-ebs-csi-driver-integration/131
> Upgrade golang version for CSI integ test

- e2e/tester/framework.go
- e2e/tester/go.mod
- e2e/tester/go.sum
- e2e/tester/pkg/cluster.go
- e2e/tester/pkg/config.go
- e2e/tester/pkg/kops.go
- e2e/tester/pkg/steps.go
Fixes #49 
Verified the POC through: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/359
Given the `test-config.yaml`, the framework can:
* create kops cluster
* run install script
* run test script
* run uninstall script
* teardown cluser
* be extensible to add eksctl support
Created this package as a sub go module so that whoever uses the tester framework don't need to bring in the whole dependencies of aws-k8s-tester. 
@wongma7 @nckturner @tiffanyfay @mogren
> Add test framework for test orchestration

- e2e/tester/pkg/config.go
- e2e/tester/pkg/kops.go
Make kops state file configurable. So that framework user could specify any s3 bucket as the state file bucket.
@gyuho 
> Make kops state file configurable

- e2e/tester/pkg/steps.go
Set -eu flag for sh so that shell exit with 1 when command fails in the middle
@gyuho @wongma7
> Set -eu flag for sh so that shell exit with 1 when command fails in the middle

- e2e/tester/framework.go
- e2e/tester/pkg/kops.go
- e2e/tester/pkg/steps.go
Add context for test workflow cancellation so that:
* the test could be cancelled and cleaned up properly
* add SIGTERM, SIGINT signal handling to cancel the test
* add timeout to cancel the test
*Test:*
* tested cleanup after a short timeout (eg. 1 min)
* tested cleanup by sending SIGTERM to the main 
> Add context for test workflow cancellation

- e2e/tester/pkg/kops.go
Alb ingress e2e test relies on eks vpc cni plugin to work.
@gyuho 
> Swtich to use vpc cni plugin

- cmd/aws-k8s-tester/eks/create.go
- eks/eks.go
- Create cluster and create config allows env var overrides.  Fixes: https://github.com/aws/aws-k8s-tester/issues/63
- Remove extra ValidateAndSetDefaults() which gets called twice
in the current create cluster path.
> Allow create to use env overrides

- e2e/tester/cmd/k8s-e2e-tester/main.go
- e2e/tester/go.mod
This helps removing the main function in each individual projects. For each consuming project, it should just need to do:
```sh
GO111MODULE="on" go get github.com/aws/aws-k8s-tester/e2e/tester/cmd/k8s-e2e-tester@master
TESTCONFIG=./tester/single-az-config.yaml ${GOPATAH}/bin/k8s-e2e-tester
```
I'm using master branch as an example. In practice, the `@v1.x.y` suffix should be used to pin the released version of the e2e tester
/cc @M00nF1sh @gyuho 
> Add main to e2e tester

- pkg/fileutil/fileutil.go
Adds a file stat check to ensure we only attempt to do a chmod on the
`aws` CLI executable if it does not already have execute permissions.
Closes Issue #66
> Only attempt chmod of `aws` CLI if not executable

- eks/alb/alb.go
- eks/eks.go
- eks/jobs/jobs.go
- eks/nlb/nlb.go
There was a problem with ALB/NLB resources not being cleaned up
when an EKS cluster was deleted by aws-k8s-tester. It turned out that
the subtester objects that create/delete resources like the ALB2048
Deployment were not being constructed properly if the
`aws-k8s-tester delete cluster` command was run. Previously, these
subtester objects were only created in `Tester.up()` which is not called
when `Tester.down()` is called.
This commit moves construction of these subtester objects into the
construction of the primary Tester object, which alleviates the issue
with non-initialized subtesters in `Tester.down()`. In doing so, I've
changed the construction of the subtester objects to take a pointer
to the `Tester` instance and grab their K8sClientSets from that
instance.
Issue #70 
By …
> ensure subtester jobs are torn down properly

- cmd/aws-k8s-tester/eks/create.go
fixes #82 
Sync() will nil not-enabled addons and fail `UpdateFromEnv()`. However, it's not necessary to sync default config and we can remove it. At the end of the function, `cfg.ValidateAndSetDefaults` will sync configuration with overrides from environment variables to file.
> Don't sync default config before UpdateFromEnv()

- go.mod
- go.sum
I need this commit to work with the latest grpc change in EFS driver. And this is picked up in etcd 3.4 but not 3.3. 
https://github.com/etcd-io/etcd/pull/11564
`go build ./...` works. 
> Using etcd 3.4

- vendor/modules.txt
Fix
```
go: inconsistent vendoring in /home/ANT.AMAZON.COM/leegyuho/go/src/github.com/aws/aws-k8s-tester:
github.com/aws/aws-sdk-go@v1.31.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/cihub/seelog@v0.0.0-20170130134532-f561c5e57575: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/davecgh/go-spew@v1.1.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/dustin/go-humanize@v1.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/fatih/color@v1.9.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
github.com/go-ini/ini@v1.55.0: is explicitly required in go.mod, but not marked …
```
> vendor: update modules.txt

- e2e/tester/pkg/kops.go
*Description of changes:* don't download hardcoded kops 1.14 alpha. download hardcoded 1.17 instead. Probably this should be configurable but not interested in figuring out how to pipe it through at the moment ~.~
> Download kops v1.17.0

- Dockerfile
- README.md
- eksconfig/config.go
- eksconfig/default.yaml
- eksconfig/env_test.go
- pkg/k8s-client/eks-deprecate/deprecate.go
- pkg/k8s-client/eks_test.go
- pkg/k8s-object/node_test.go
- use 1.17 kubectl 
-  watch out for 1.17 deprecated apis
> use 1.17 kubectl and add 1.17 deprecated apis

- ec2/ec2.go
- ec2config/config.go
- eks/cluster/cluster.go
- eks/cluster/encryption.go
- eks/cluster/role.go
- eks/cluster/vpc.go
- eks/eks.go
- eks/mng/version-upgrade/version-upgrade.go
- eksconfig/config.go
Use the "disable" feature of `colorstring` to avoid duplicating all
the format strings, just for the non-colored case.
Also enable the "reset" feature, so colored strings are automatically
reset at the end of each message.  This obsoletes the explicit
`[default]` statements, so remove those too.
> Remove duplication of colorized format strings

- ec2/ec2.go
- eks/cluster/cluster.go
- eks/cluster/encryption.go
- eks/cluster/role.go
- eks/cluster/vpc.go
- eks/eks.go
- eks/mng/version-upgrade/version-upgrade.go
The mechanical process used to create #101 accidentally reversed the
order of log messages.  Oops.  This change restores the
correct (original) order.
Fixes PR #101
> Fix accidental reversal of colorized log messages

- CHANGELOG/CHANGELOG-1.4.md
- eks/ng/autoscaler/cluster-autoscaler.go
- eks/ng/ng.go
- eks/ng/nodes.go
- eks/ng/role.go
- eksconfig/add-on-node-groups.go
- eksconfig/config.go
- eksconfig/env_test.go
add cluster autoscaler addon.
Clusteraddon tests can be enabled like any other addon by setting env variable
It's disabled by default.
> add cluster autoscaler addon

- eksconfig/add-on-irsa.go
IRSA comes up with 10 replicas by default which uses significant resources. It should default to something smaller.
> Reduced IRSA default replicas to something more reasonable

- eks/cw-agent/cw-agent.go
- eks/cw-agent/cw-agent_test.go
- eks/cw-agent/tester.go
- eks/eks.go
- eks/fluentd/fluentd.go
- eks/fluentd/fluentd_test.go
- eks/fluentd/tester.go
- eks/mng/role.go
- eks/ng/role.go
- eks/php-apache/php-apache.go
- eksconfig/README.md
- eksconfig/add-on-cw-agent.go
- eksconfig/add-on-fluentd.go
- eksconfig/add-on-php-apache.go
- eksconfig/config.go
- eksconfig/default.yaml
- eksconfig/env.go
- eksconfig/env_test.go
- eksconfig/gen/main.go
Automate
- https://github.com/aws-samples/amazon-cloudwatch-container-insights/tree/master/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-logs.html
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html
```
AWS_K8S_TESTER_EKS_ON_FAILURE_DELETE=true \
AWS_K8S_TESTER_EKS_REGION=us-west-2 \
AWS_K8S_TESTER_EKS_LOG_COLOR=true \
AWS_K8S_TESTER_EKS_S3_BUCKET_CREATE=true \
AWS_K8S_TESTER_EKS_PARAMETERS_ENCRYPTION_CMK_CREATE=true \
AWS_K8S_TESTER_EKS_PARAMETERS_ROLE_CREATE=true \
AWS_K8S_TESTER_EKS_PARAMETERS_VERSION=1.16 \
AWS_K8S_TESTER_EKS_PARAMETERS_VPC_CREATE=true \
AWS_K8S_TESTER_EKS_CLIENTS=5 \ …
```
> Add Fluentd add-on

- CHANGELOG/CHANGELOG-1.4.md
- eks/eks.go
- eksconfig/README.md
- eksconfig/config.go
- eksconfig/default.yaml
- eksconfig/env_test.go
- eksconfig/status.go
Partially address https://github.com/aws/aws-k8s-tester/issues/123.
Short-term solution without breaking changes.
> *: support "AWS_K8S_TESTER_EKS_SKIP_DELETE_CLUSTER_AND_NODES"

- eksconfig/add-on-managed-node-groups.go
- eksconfig/add-on-node-groups.go
```
failed to validate configuration "test.yaml" (validateAddOnNodeGroups failed [AddOnNodeGroups.RoleServicePrincipals ["ec2.amazonaws.com.cn" "eks.amazonaws.com" "eks-fargate-pods.amazonaws.com" "eks-dev.aws.internal" "eks-beta-pdx.aws.internal" "eks-fargate-pods.aws.internal"] must include 'ec2.amazonaws.com'])
```
To support `aws-k8s-tester` test against other regions, add extra validation for NodeGroup and ManagedNodegroup RoleServicePrincipals.
> Add support for validate MNG + NG RoleServicePrincipals 

- CHANGELOG/CHANGELOG-1.4.md
- Makefile
- cmd/aws-k8s-tester/eks/create-hollow-nodes.go
- eks/hollow-nodes/hollow-nodes.go
- eks/hollow-nodes/remote/hollow-nodes.go
- eksconfig/add-on-hollow-nodes-remote.go
- eksconfig/config.go
- Deploys to kubemark namespace
- Uses a replication controller instead of deployment
- Correctly names Kubemark pods to equal node names
- Adds correct node labels for CA discovery.
- Idempotently Create/Update kubemark resources.
> Redesigned hollow nodes to be compatible with Cluster Autoscaler's Kubemark integration

- Dockerfile
- Makefile
- eks/hollow-nodes/hollow-nodes.go
- scripts/build.sh
```
make
```
```
WHAT=aws-k8s-tester TARGETS=darwin RELEASE_VERSION=latest ./scripts/build.sh
GIT_COMMIT: c7f87803ce5d
RELEASE_VERSION: latest
BUILD_TIME: 2020-07-22_18:49:11
Usage: `make TARGET='linux' WHAT='aws-k8s-tester cw-utils'`
DEFAULT_TARGETS=linux darwin
DEFAULT_WHAT=aws-k8s-tester cw-utils ec2-utils ecr-utils eks-utils etcd-utils s3-utils sts-utils
=== Building target=aws-k8s-tester, os=darwin ===
Success! Your shiny new binaries are ready.
find ./bin -type f
```
> Improvements to Makefile and build scripts. Hollow nodes now supports >1 pod per node and taints those nodes.

- eksconfig/config.go
AWS_K8S_TESTER_EKS_CONFIG="
spec:
clusterAutoscaler:
cloudProvider: kubemark
image: 767520670908.dkr.ecr.us-west-2.amazonaws.com/cluster-autoscaler-kubemark:custom-build-20200727
overprovisioning:
kubemarkEnabled: true
" \
AWS_K8S_TESTER_EKS_ON_FAILURE_DELETE=false \
AWS_K8S_TESTER_EKS_ADD_ON_NODE_GROUPS_ENABLE=true \
AWS_K8S_TESTER_EKS_ADD_ON_NODE_GROUPS_ROLE_CREATE=true \
AWS_K8S_TESTER_EKS_ADD_ON_NODE_GROUPS_ASGS='{"default":{"name":"default","remote-access-user-name":"ec2-user","ami-type":"AL2_x86_64","image-id":"","image-id-ssm-parameter":"/aws/service/eks/optimized-ami/1.16/amazon-linux-2/recommended/image_id","instance-types":["c5.xlarge"],"volume-size":40,"asg-min-size":3,"asg-max-size":3,"asg-desired-capacity":3,"kubelet-extra-args":"","cluster-autoscaler":{"enable":true}}}' \ …
> Adds config-as-yaml as a new environment variable AWS_K8S_TESTER_EKS_CONFIG

- CHANGELOG/CHANGELOG-1.5.md
- eks/cni-vpc/cni-vpc.go
ref. https://github.com/aws/amazon-vpc-cni-k8s/pull/1107
> eks/cni-vpc: remove unused docker.sock

- CHANGELOG/CHANGELOG-1.5.md
- ec2/asgs.go
- ec2/asgs_test.go
- ec2config/validate-defaults.go
- eks/gpu/gpu.go
- eks/mng/nodes.go
- eks/mng/version-upgrade/version-upgrade.go
- eks/mng/wait/wait.go
- eks/ng/nodes.go
- eks/ng/nodes_test.go
- eks/ng/wait/wait.go
- eksconfig/add-on-managed-node-groups.go
- eksconfig/add-on-node-groups.go
Either of these two defaults:
1. desired 10, min 0, max  0 ==> desired 10, min 10, max 10
2. desired  0, min 1, max 10 ==> desired  0, min  1, max 10
Either desired or min must be >0.
> *: set desired capacity defaults

- eks/eks.go
- eks/metrics-server/addon.go
- eks/metrics-server/metrics-server.gotmpl
- eksconfig/metrics-server.go
- eksconfig/spec.go
- eksconfig/status.go
I refactored metrics-server to implement the Addon interface using overprovisioning and clusterautoscaler as references. Now, we can include `metrics-server` in the spec for `AWS_K8S_TESTER_EKS_CONFIG`.
> Refactor metrics-server to implement Addon interface

- CHANGELOG/CHANGELOG-1.5.md
- ec2/asgs.go
- eks/clusterautoscaler/clusterautoscaler.go
- eks/eks.go
- eks/mng/wait/wait.go
- eks/ng/wait/wait.go
- pkg/aws/ec2/ec2.go
Fix a case when ASG has >500 instances and some instances become stale while polling.
Tests:
```
{"level":"info","ts":"2020-08-05T19:31:50.408-0700","caller":"wait/wait.go:71","msg":"checking ASG","asg-name":"eks-2020080519-charismau3mi-ng-al2-cpu-c518xlarge"}
{"level":"info","ts":"2020-08-05T19:31:50.873-0700","caller":"ec2/ec2.go:29","msg":"polling ASG","asg-name":"eks-2020080519-charismau3mi-ng-al2-cpu-c518xlarge","ctx-time-left":"1h33m19.999997228s"}
{"level":"info","ts":"2020-08-05T19:32:01.535-0700","caller":"ec2/ec2.go:103","msg":"polling instance status","target-total":500,"ctx-time-left":"24m59.999955031s"}
{"level":"info","ts":"2020-08-05T19:32:11.536-0700","caller":"ec2/ec2.go:126","msg":"describing batch","batch-total":30} …
```
> pkg/aws/ec2: add "WaitUntilRunning"

- pkg/aws/ec2/ec2.go
Fix the case creating 2-node ASG fails due to timeouts:
```
{"level":"info","msg":"checking ASG","asg-name":"eks-2020081315-everesttishn-ng-al2-cpu"}
{"level":"info","msg":"polling ASG until all EC2 instances are running","asg-name":"eks-2020081315-everesttishn-ng-al2-cpu","ctx-time-left":"10m19.999996088s"}
{"level":"info","msg":"polling instance status","target-total":2,"ctx-time-left":"5.999992891s"}
{"level":"warn","msg":"failed to poll instance status; retrying","error":"context deadline exceeded"}
{"level":"info","msg":"polling instance status","target-total":2,"ctx-time-left":"5.999993504s"}
{"level":"warn","msg":"failed to poll instance status; retrying","error":"context deadline exceeded"}
{"level":"info","msg":"polling instance …
```
> pkg/aws/ec2: set minimum wait time for ec2 polling

- eks/cluster-loader/clusterloader2/addon.go
- eksconfig/cluster-loader.go
In clusterloader2, there are some basic flags that drive the shared functionality between different test configurations, such as --nodes or --report-dir, but to further configure your test, you'd need to change your variables in the yaml, such as having a pods_per_node, num_of_namespaces, or enable_chaosmonkey variables. This allows total automation of tests, and by adding override fields, you can configure the test just as well as if it was in the CLI.
> CL2 TestOverrides capabilities added

- CHANGELOG/CHANGELOG-1.5.md
- eks/mng/nodes.go
- eksconfig/add-on-cluster-loader-local.go
- eksconfig/add-on-cluster-loader-remote.go
- go.mod
- go.sum
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/service/s3/api.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload_input.go
- vendor/modules.txt
> eks/mng: fix MNG desired capacity

- Dockerfile
While running prow jobs, the add-on templates cannot be read as they are not copied into the filesystem. As the EKS folder will be able to host different future add-ons and is not limited to the current 4 implemented, copying the folder provides a general solution that provides the same filesystem logic as if running on a local machine. 
Additionally, the eks folder only adds 5MB to the dockerfile, which is already ~750MB.
> Added EKS folder to Dockerfile for prow job filesystem fix

- CHANGELOG/CHANGELOG-1.5.md
- eks/cluster/cluster.go
- go.mod
- go.sum
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/service/eks/api.go
- vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/doc.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/pool.go
- vendor/github.com/aws/aws-sdk-go/service/ssm/api.go
- vendor/github.com/aws/aws-sdk-go/service/sts/api.go
- vendor/github.com/aws/aws-sdk-go/service/sts/doc.go
- vendor/github.com/jmespath/go-jmespath/.travis.yml
- vendor/github.com/jmespath/go-jmespath/Makefile
- vendor/github.com/jmespath/go-jmespath/go.mod
- vendor/github.com/jmespath/go-jmespath/go.sum
- vendor/modules.txt
HTTP GET failure due to bad packet or packet loss should be retried.
Fix the following panic:
```
{"level":"info","ts":"2020-09-25T23:43:56.457-0700","caller":"cluster/cluster.go:700","msg":"updating host with port :443","host":"..."}
{"level":"info","ts":"2020-09-25T23:43:56.457-0700","caller":"cluster/cluster.go:711","msg":"fetching OIDC CA thumbprint","url":"https://...:443/test/id/78FD753967D735CEFC309F15590F617F"}
{"level":"warn","ts":"2020-09-25T23:44:38.734-0700","caller":"cluster/cluster.go:720","msg":"failed to fetch OIDC CA thumbprint","url":"https://...:443/test/id/78FD753967D735CEFC309F15590F617F","error":"Get \"https://...:443/test/id/78FD753967D735CEFC309F15590F617F\": local error: tls: bad record MAC"}
panic: runtime error: invalid memory address or nil pointer dereference …
```
> eks/cluster: fix OIDC CA thumbprint fetch 

- eks/cluster-loader/clusterloader2/cluster-loader.gotmpl
- eks/cluster-loader/configs/cluster-autoscaler/hollowdeployment.yaml
- eks/clusterautoscaler/clusterautoscaler.go
- Added backoffLimit so that CL2 addon test doesn't retry
- Changed default deployment.yaml to be real nodes (not hollow-nodes)
- Added hollowdeployment.yaml for option for hollow-nodes
- Fixed a CA add-on error where maxNodes was mis-coded as minNodes.
> Changed CL2 test add-on to not retry on failure, and fixed CA add-on max nodes error

- CHANGELOG/CHANGELOG-1.5.md
- eks/cluster-loader/clusterloader2/addon.go
- eks/cluster-loader/clusterloader2/cluster-loader.gotmpl
- eks/cluster-loader/configs/cluster-autoscaler/config.yaml
- eks/cluster/vpc.go
- eks/ng/nodes.go
- eksconfig/cluster-loader.go
- eksconfig/config.go
- Expanded VPC default CIDR range in order to support more pods for larger scale tests
- Previous VPC defaults had one /19 CIDR Block, allowing for 8k pods. Added multiple blocks of max VPC Block size (/16).
- Changed VPCs from 192 space to 10 space.
- Subnets are by default same CIDR range as VPC Blocks, but can be changed with environment variables
- Public Subnets are /16 blocks by default
- Private Subnets are /17 blocks by default
*Testing*
- Tested by bringing up a cluster to a larger size than before to see if VPC was able to handle more IPs than before the change. VPC was brought up successfully, and more IPs were successfully utilized.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> Changed VPC defaults to be multiple blocks to account for larger testing clusters

- eks/cluster-loader/cluster-loader.go
Increase clusterloader test timeout from 20 min to 120 min. This will be configurable in the future.
> Increase clusterloader test timeout from 20 min to 120 min

- eks/cluster/vpc.go
This causes issue with AZ index 2 lookup on VPC creation:
`Fn::Select cannot select nonexistent value at index 2`
>  Set us-west-1 to 2 AZ region for VPC creation

- eks/ng/nodes.go
- eksconfig/add-on-node-groups.go
- eksconfig/env_test.go
Exposes configuration for additional bootstrap args and makes region specific adjustments required for special regions.
> Support passing additional args to worker bootstrap script. Update NG CFN for special regions.

- ec2/asgs.go
```
ASGDesiredCapacity:
Type: Number
Description: Desired size auto scaling group
Default: 1
MinValue: 1
MaxValue: 1000
```
Fix 
> "Parameter 'ASGDesiredCapacity' must be a number not less than 1\n\tstatus code: 400"
> ec2: fix "ASGDesiredCapacity" template

- eks/conformance/conformance.go
- eksconfig/add-on-conformance.go
- eksconfig/env_test.go
n/a
By default, `sonobuoy/sonobuoy` & `sonobuoy/systemd-logs` are pulled from Dockerhub. This change adds the option to override this behavior and provide a custom images.
```
hack/eksconfig.gen.sh 
...
aws-k8s-tester eks create config --path "./eksconfig/default.yaml"' success`
```
> *: expose configuration of sonobuoy worker/systemd-logs container overrides

- eks/conformance/conformance.go
- eksconfig/add-on-conformance.go
- eksconfig/env_test.go
na
Special image config is required for airgapped regions
*Testing*
`'aws-k8s-tester eks create config --path "./eksconfig/default.yaml"' success`
> conformance: expose sonobuoy e2e-repo-config flag

- eks/amazon-eks-ami-issue-454/README.md
- eks/amazon-eks-ami-issue-454/soft-lockup-454.go
- eks/eks.go
- eksconfig/add-on-ami-soft-lockup-issue-454.go
- eksconfig/config.go
- eksconfig/env.go
*Issue #, if available:* None
This adds a test that verifies [an issue tracked in the amazon-eks-ami repo](https://github.com/awslabs/amazon-eks-ami/issues/454) continues to stay fixed. The original issues causes a soft lockup in the node and it becomes unresponsive.
> Adds test for amazon-eks-ami issue 454 to test a soft lockup bug

- CHANGELOG/CHANGELOG-1.5.md
- eks/mng/mng.go
Fix https://github.com/aws/aws-k8s-tester/issues/195.
> eks/mng: fix MNG delete by ignoring error on first delete try

- eks/ng/nodes.go
*Issue #, if available:* N/A
```
[/Parameters/ImageIDSSMParameter] 'null' values are not allowed in templates
```
*Description of changes:* fix indentation for ImageIDSSMParameter
> eks/ng/nodes.go: fix indentation for ImageIDSSMParameter

- eks/eks.go
- eksconfig/config.go
- pkg/aws/aws.go
The AWS Go SDK has not been updated to include ap-northeast-3. This is a workaround to use aws-k8s-tester against KIX without having to update the SDK.
*Testing:*
Previously we'd fail to run create cluster in KIX:
```
AWS_K8S_TESTER_EKS_ON_FAILURE_DELETE=true \
AWS_K8S_TESTER_EKS_REGION=ap-northeast-3 \
AWS_K8S_TESTER_EKS_LOG_COLOR=true \
AWS_K8S_TESTER_EKS_S3_BUCKET_CREATE=true \
AWS_K8S_TESTER_EKS_S3_BUCKET_CREATE_KEEP=false \
AWS_K8S_TESTER_EKS_PARAMETERS_ENCRYPTION_CMK_CREATE=true \
AWS_K8S_TESTER_EKS_PARAMETERS_ROLE_CREATE=true \
AWS_K8S_TESTER_EKS_PARAMETERS_ROLE_SERVICE_PRINCIPALS="ec2.amazonaws.com,eks.amazonaws.com,eks-fargate-pods.amazonaws. …
```
> Ignore error when region is missing from the given partition

- eksconfig/add-on-conformance.go
Update sonobuoy tool version to run 1.19 conformance tests. 
Before sonobuoy version output shows this and logs have this warning
```
'sonobuoy version' output:
Sonobuoy Version: v0.18.3
MinimumKubeVersion: 1.16.0
MaximumKubeVersion: 1.18.99 <- Maximum is < 1.19
...
time="2021-02-17T12:44:53-08:00" level=warning msg="The maximum supported Kubernetes version is 1.18.99, but the server version is v1.19.6-eks-49a6c0. Sonobuoy will continue but unexpected results may occur."
```
After updating the tool version, sonobuoy version supports 1.19 and warning log goes away. 
Pulling conformance test image from gcr.io/google-containers throws errors such as 
```
docker pull gcr.io/google-containers/conformance:v1.19.0
Error response from daemon: …
```
> Update sonobuoy tool version to 1.19 and e2e image repo to k8s.gcr.io

- cmd/aws-k8s-tester/eks/create-stresser-v2.go
- cmd/aws-k8s-tester/eks/create.go
- eks/eks.go
- eks/stresser2/stresser.go
- eksconfig/add-on-stresser-remote-v2.go
- eksconfig/config.go
- eksconfig/env.go
- eksconfig/env_test.go
- pkg/aws/awscurl/awscurl.go
- pkg/aws/awscurl/types.go
Added stresser v2 add on to keep updating one k8s resource until reaching etcd limit. 
```bash
AWS_K8S_TESTER_EKS_ADD_ON_STRESSER_REMOTE_V2_ENABLE=true \
AWS_K8S_TESTER_EKS_ADD_ON_STRESSER_REMOTE_V2_REPOSITORY_ACCOUNT_ID=730249423355 \
AWS_K8S_TESTER_EKS_ADD_ON_STRESSER_REMOTE_V2_REPOSITORY_NAME=aws/aws-k8s-tester \
AWS_K8S_TESTER_EKS_ADD_ON_STRESSER_REMOTE_V2_REPOSITORY_IMAGE_TAG=latest \
AWS_K8S_TESTER_EKS_ADD_ON_STRESSER_REMOTE_V2_REPOSITORY_BUSYBOX_NAME=busybox \
AWS_K8S_TESTER_EKS_ADD_ON_STRESSER_REMOTE_V2_REPOSITORY_BUSYBOX_IMAGE_TAG=latest \
AWS_K8S_TESTER_EKS_ADD_ON_STRESSER_REMOTE_V2_SCHEDULE='0 */6 * * *' \
AWS_K8S_TESTER_EKS_ADD_ON_STRESSER_REMOTE_V2_PARALLELS=10 \
AWS_K8S_TESTER_EKS_ADD_ON_STRESSER_REMOTE_V2_COMPLETES=10 \ …
```
> Stresser v2

- CHANGELOG/CHANGELOG-1.5.md
- ec2/ec2.go
- ec2config/README.md
- ec2config/config.go
- ec2config/default.yaml
- ec2config/env_test.go
- ec2config/validate-defaults.go
- eks/eks.go
- eksconfig/README.md
- eksconfig/config.go
- eksconfig/default.yaml
- eksconfig/env_test.go
Fix https://github.com/aws/aws-k8s-tester/issues/211.
> config: change LogColorOverride to "string"

- eks/cluster/vpc.go
- eks/cluster/vpc_test.go
n/a
Tags are not supported when creating EIPs via CFN in isolated partitions.
Successfully ran conformance tests in region with these changes.
Manually tested setting `IsIsolated` to false and it produces valid EIPs w/ tag:
```yaml
NATGatewayEIP1:
Type: AWS::EC2::EIP
DependsOn:
- VPC
- VPCGatewayAttachment
Properties:
Domain: vpc
Tags:
- Key: Name
Value: !Sub '${AWS::StackName}-EIP1'
```
`'aws-k8s-tester eks create config --path "./eksconfig/default.yaml"' success`
> cluster: remove AWS::EC2::EIP.Properties.Tags in isolated partitions

- eks/conformance/conformance.go
- eksconfig/README.md
- eksconfig/add-on-conformance.go
- eksconfig/env_test.go
If we need run upstream conformance test against to specific groups, we need add focus or skip as [flags for sonobuoy](https://sonobuoy.io/docs/master/e2eplugin/).
*Tests*
```
{"msg":"Test Suite completed","total":32,"completed":32,"skipped":5635,"failed":0}
Ran 32 of 5667 Specs in 468.099 seconds
SUCCESS! -- 32 Passed | 0 Failed | 0 Pending | 5635 Skipped
PASS
```
```
Focus on sig-network tests
AWS_K8S_TESTER_EKS_ADD_ON_CONFORMANCE_SONOBUOY_E2E_FOCUS="sig-network.*\[Conformance\]"
sonobuoy-e2e-focus: sig-network.*\[Conformance\]
sonobuoy-e2e-repo-config: ""
sonobuoy-e2e-skip: ""
Plugin: e2e
Status: passed
Total: 5667
Passed: 32
Failed: 0
Skipped: 5635
Plugin: systemd-logs
Status: passed
Total: 5
Passed: 5
Failed: 0
Skipped: 0 …
```
> Adding e2e focus and skip for sonobuoy as flags.

- k8s-tester/cloudwatch-agent/tester.go
- k8s-tester/fluent-bit/fluent-bit.go
- k8s-tester/metrics-server/tester.go
Signed-off-by: jonahjon <jonahjones094@gmail.com>
- CW agent had an old node selector that caused it to timeout
- Metrics server image version, and API version are outdated causing control plane issues
- Fixing string formatting from fluent-bit tests
> Fixes from running eks-a beta tests with k8s-tester

- eks/cluster-loader/configs/cluster-autoscaler/config.yaml
Was getting the following error when running clusterloader:
```
F0720 09:26:45.223452   72877 clusterloader.go:337] Test compilation failed: [steps[2].measurements: Invalid value: []*api.Measurement(nil): can't be empty with empty phases
steps[4].measurements: Invalid value: []*api.Measurement(nil): can't be empty with empty phases
steps[6].measurements: Invalid value: []*api.Measurement(nil): can't be empty with empty phases
steps[9].measurements: Invalid value: []*api.Measurement(nil): can't be empty with empty phases
steps[11].measurements: Invalid value: []*api.Measurement(nil): can't be empty with empty phases]
```
Just fixing the yaml formatting.
By submitting this pull request, I confirm that my contribution is made under the terms …
> fix misformatted eks/cluster-loader/configs/cluster-autoscaler/config

- k8s-tester/conformance/sonobuoy.go
- k8s-tester/conformance/tester.go
Signed-off-by: jonahjon <jonahjones094@gmail.com>
For EKS-A hitting docker pull limits since the control plane IP endpoint is likely the only input/output for docker pull from docker hub. This changes the test image to an ECR mirror to get around the throttling.
> EKS-A conformance fix

- ec2config/config.go
- ec2config/env_test.go
- eks/ng/asg.go
- eksconfig/add-on-node-groups.go
- eksconfig/config.go
- eksconfig/env_test.go
Making VolumeType configurable in AddonNodeGroups. Currently instance types in node groups default to gp3 for the EBS volume type and this volume type is not available in all regions including DCA and LCK. 
*Testing*
Unit tests:
eksconfig/env_test.go:
```
$ go test -v -run Test*
...
PASS
ok      github.com/aws/aws-k8s-tester/eksconfig 0.814s
```
ec2config/env_test.go:
```
$ go test -v -run Test*
...
PASS
ok      github.com/aws/aws-k8s-tester/ec2config 0.076s
```
Testing that we can explicitly set gp2:
```
AWS_K8S_TESTER_EKS_ADD_ON_NODE_GROUPS_ASGS='{"GetRef.Name-ng-al2-cpu":{"name":"GetRef.Name-ng-al2-cpu","remote-access-user-name":"ec2-user","ami-type":"AL2_x86_64","image-id":"","image-id-ssm-parameter":"/aws/service/eks/optimized-ami/1.19/amazon-linux-2/recommen …
```
> Making VolumeType configurable in AddonNodeGroups

- eksconfig/add-on-managed-node-groups.go
- eksconfig/config.go
- Add support for ARM AMI type in managed node group creation
- Add support for ARM AMI type in managed node group creation
> Add support for ARM AMI type in managed node group

- eks/metrics-server/metrics-server.gotmpl
* metrics-server wasn't working on 1.22 due to the removal of `apiregistration.k8s.io/v1beta1`, so I upgraded to the https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.6.1 release.
* compatible with 1.19+
> Update metrics-server to v0.6.1

- Makefile
- cmd/kubetest2-aws/README.md
- cmd/kubetest2-aws/deployer/deployer.go
- cmd/kubetest2-aws/main.go
- go.mod
- go.sum
Adding kubetest2 aws deployer using the existing eks framework in this repository.
> Kubetest2-eks support

- eksconfig/config.go
- eksconfig/default.yaml
Updates the default EKS version to 1.27, from 1.20 (🕸️).
> Update default EKS version to 1.27

- Dockerfile
- Makefile
- hack/build.sh
Current build process is broken as it tries to pull some artifacts from upstream s3 buckets, but they are no longer existing.
Fix the broken build process. In addition, add a few build arguments that help customize the built AKT image.
> Fix broken build; support customization

- .github/workflows/ci.yaml
Adds a workflow that will ensure PR's don't break the build.
> Add CI/build workflow

- README.md
The PR is a quick fix updating the link to the [KEP 2313: aws-k8s-tester - kubetest plugin for AWS and EKS](https://github.com/kubernetes/enhancements/blob/master/keps/provider-aws/2313-aws-k8s-tester/README.md)
> fix link to the KEP 2313

- .github/workflows/ci.yaml
- Dockerfile.kubetest2
- e2e2/.dockerignore
- go.work
- go.work.sum
- hack/build.sh
Adds the entire source tree to the kubetest2 docker image, so that `go test` can be used with the `exec` tester.
Also switches to the v2 AWS CLI, so that `aws eks get-token` returns the correct `apiVersion`.
> Add src to Dockerfile.kubetest2, use AWS CLI v2

- kubetest2/internal/deployer/eksapi/deployer.go
- kubetest2/internal/deployer/eksapi/kubeconfig.go
Removes dependency on the AWS CLI to get up the kubeconfig, has better handling of EKS endpoint overrides.
> Fix kubeconfig handling

- kubetest2/README.md
- kubetest2/internal/testers/multi/cmd.go
- kubetest2/kubetest2-tester-multi/main.go
Adds a new tester that wraps execution of multiple testers.
> Add kubetest2-tester-multi

- kubetest2/go.mod
- kubetest2/go.sum
- kubetest2/internal/deployer/eksapi/aws.go
- kubetest2/internal/deployer/eksapi/cluster.go
- kubetest2/internal/deployer/eksapi/deployer.go
- kubetest2/internal/deployer/eksapi/infra.go
- kubetest2/internal/deployer/eksapi/janitor.go
- kubetest2/internal/deployer/eksapi/nodegroup.go
The VPC CNI periodically cleans up unused ENI's, but if the `Deployment` goes down before this happens, remaining ENI's can prevent deletion of the `kubetest2-eksapi` infrastructure stack.
> Delete ENIs leaked by VPC CNI

- kubetest2/internal/deployer/eksapi/infra.go
Filters ENIs for `detached` status before trying to delete them.
> Only sweep detached ENIs of type `interface`

- kubetest2/internal/deployers/eksapi/cloudformation/infra.yaml
- kubetest2/internal/deployers/eksapi/cluster.go
- kubetest2/internal/deployers/eksapi/deployer.go
N/A
Enable eks api deployer to provision an ipv6 cluster.  By default it falls back to `ipv4` if `--ip-family` option is not  passed
> Provision IPv6 clusters via eks api deployer

- Dockerfile.kubetest2
So the `--generate-ssh-key` flag for the `eksapi` deployer is functional in the container image.
> Add ssh-keygen to kubetest2 image

- kubetest2/internal/deployers/eksapi/ssh.go
- kubetest2/internal/deployers/eksapi/ssh_test.go
Uses the go stdlib to generate a key instead of `ssh-keygen`, which really prefers a tty.
> Generate SSH key with go instead of exec

- kubetest2/go.mod
- kubetest2/go.sum
- kubetest2/internal/deployers/eksapi/cluster.go
- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/infra.go
- kubetest2/internal/deployers/eksapi/janitor.go
- kubetest2/internal/deployers/eksapi/kubeconfig.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
Reorganizes infra/cluster/nodegroup logic into "managers". Also uses the DeployerWithInit interface from kubetest2 to clean up the lifecycle of the awsClients, etc.
> Refactor eksapi deployer with initializer, managers

- kubetest2/internal/deployers/eksapi/infra.go
- kubetest2/internal/deployers/eksapi/janitor.go
Increases the infra stack creation + deletion timeouts to 15 minutes, this can take a bit longer in the `aws-us-gov` partition.
Also continues the janitor loop when an error occurs, so a stuck stack doesn't block cleanup.
> Increase infra timeouts, don't fail-fast in janitor

- kubetest2/go.mod
- kubetest2/go.sum
- kubetest2/internal/deployers/eksapi/aws.go
- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
Adds a flag to specify an expected node AMI ID. If the actual nodes launched are not using the expected AMI, the deployer will fail.
> Add --expected-ami option to eksapi deployer

- kubetest2/internal/deployers/eksapi/deployer.go
This instance type is not yet available in all partitions.
> Remove m7i.large from default instance types

- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup.yaml.template
The `kubernetes.io/cluster/$CLUSTER_NAME: owned` tag is required by Kubelet's legacy in-tree cloud provider, which is used on the EKS AMI for Kubernetes 1.25 and below.
> Add required tags to ASG for 1.25-

- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup.yaml.template
Even when this CFN template parameter is not required (`AMIId` is defined), the default value is resolved. This will fail for Kubernetes versions that aren't GA on EKS yet (i.e. the SSM parameter doesn't exist yet).
We intend to always pass an AMI ID to this template, so I'm just removing this template parameter.
> Remove AMISSMParameter option from unmanaged nodegroup template

- kubetest2/internal/deployers/eksapi/deployer.go
This performs leaked ENI cleanup before cluster deletion. The security group created by EKS will be associated with leaked ENIs, and the async cluster deletion process will leave the security group behind. This, in turn, will prevent VPC deletion when the infra stack is torn down.
> Delete leaked ENIs before cluster

- kubetest2/internal/deployers/eksapi/infra.go
ENIs for the control plane will be created in private subnets, so we need to filter for ENIs that were created only by the VPC CNI when trying to do our cleanup.
> Filter ENIs based on VPC CNI applied tag

- kubetest2/go.mod
- kubetest2/go.sum
- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/infra.go
- kubetest2/internal/deployers/eksapi/janitor.go
- kubetest2/internal/metrics/cloudwatch.go
- kubetest2/internal/metrics/noop.go
- kubetest2/internal/metrics/registry.go
- kubetest2/kubetest2-eksapi-janitor/main.go
Adds a metric registry that collects all values and emits then when called. A cloudwatch and no-op implementation are provided.
CloudWatch charges per-PutMetricData call, so the registry is intended to minimize these calls.
Metrics are also added in this PR for the `eksapi` deployer:
- infrasructure stack deletion failures
- leaked ENI's found when deleting infrastructure stack
> Add metrics registry to kubetest2-eksapi

- kubetest2/internal/deployers/eksapi/cluster.go
- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/k8s.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
- kubetest2/internal/deployers/eksapi/templates/templates.go
- kubetest2/internal/deployers/eksapi/templates/templates_test.go
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup.yaml.template
- kubetest2/internal/deployers/eksapi/templates/userdata_bootstrap.sh.mimepart.template
- kubetest2/internal/deployers/eksapi/templates/userdata_nodeadm.yaml.mimepart.template
- kubetest2/internal/deployers/eksapi/userdata.go
- kubetest2/internal/deployers/eksapi/userdata_test.go
Parameterizes the node user data, with support for the legacy `bootstrap.sh` and the new `nodeadm` formats.
> Add `--user-data-format` option, nodeadm support

- kubetest2/internal/deployers/eksapi/addons.go
- kubetest2/internal/deployers/eksapi/deployer.go
Adds a flag (`--addons`) that takes addon name + version pairs (e.g. `vpc-cni:v1.16.0-eksbuild.1`). The addons will be installed before node creation because the addon may be required for the nodes to stabilize.
A specific addon version can be used, or the following "markers":
- `latest`
- `default`
> Add addon management to eksapi deployer

- kubetest2/internal/deployers/eksapi/addons.go
- kubetest2/internal/deployers/eksapi/auth_map_role_test.go
- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/vpccni.go
- kubetest2/internal/deployers/eksapi/vpccni_test.go
This adds an option to increase the number of warm ENIs + IPs for the VPC CNI, which prevents flakiness when conformance testing.
> Add `--tune-vpc-cni` option to eksapi deployer

- e2e2/test/cases/nvidia/manifests/efa-device-plugin.yaml
- e2e2/test/cases/nvidia/manifests/mpi-job-pytorch-training-multi-node.yaml
- e2e2/test/cases/nvidia/mpi_test.go
- e2e2/test/images/Dockerfile.aws-efa-nccl-tests
- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
- kubetest2/internal/deployers/eksapi/templates/templates.go
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup.yaml.template
This adds a new option to the eksapi deployer, `--efa`, which will create an EFA-enabled unmanaged nodegroup.
It also adds a case to the nvidia e2e tests to perform an AllReduce operation using 2 workers on EFA-enabled nodes.
> Add EFA NCCL test case, unmanaged nodegroup template

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
add a flag to pass `ami-type` to the nodegroup creation for kubetest2 deployer
> accept amitype in kubetest2 managed nodegroup creation

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
missed a test to validate this flag, and looks like it can only parse under the `string` primitive and not the `ekstypes.AMITypes` wrapper type
Before:
```bash
$ kubetest2 eksapi --ami-type=FOO
Error: unknown flag: --ami-type
Usage:
kubetest2 eksapi [Flags] [DeployerFlags] -- [TesterArgs]
Flags:
--artifacts string         top-level directory to put artifacts under for each kubetest2 run, defaulting to "${ARTIFACTS:-./_artifacts}". If using the ginkgo tester, this must be an absolute path. (default "/home/nbakerd/workspace/aws-k8s-tester/kubetest2/_artifacts")
--build                    build kubernetes
--down                     tear down the test cluster
-h, --help                     display help
--run-id string            unique …
```
> fix ami-type flag

- kubetest2/internal/deployers/eksapi/nodegroup.go
- kubetest2/internal/deployers/eksapi/templates/templates.go
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup.yaml.template
- kubetest2/internal/deployers/eksapi/templates/userdata_bottlerocket.toml.template
- kubetest2/internal/deployers/eksapi/userdata.go
- kubetest2/internal/deployers/eksapi/userdata_test.go
Adds a new `--user-data-format` option, `bottlerocket`, which writes a TOML document (not in a MIME multi-part) containing Bottlerocket settings.
> Add bottlerocket user data format

- .github/workflows/ci.yaml
- e2e2/test/images/Dockerfile.aws-efa-nccl-tests
Update aws-efa-nccl-tests docker file to the latest cuda and nccl version. Tested with EKS cluster.
> Update aws-efa-nccl-tests docker file to the latest cuda and nccl version

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
When `--instance-types` is not specified, we set a default list of x86_64 instance types. This adds an `ec2:DescribeImages` call to determine the AMI's architecture, so that arm64 AMI's don't always require an `--instance-types` override.
> Determine default instance types based on AMI architecture

- e2e2/internal/framework_extensions/client.go
- e2e2/test/cases/nvidia/main_test.go
- e2e2/test/cases/nvidia/manifests/mpi-job-nccl-test-multi-node.yaml
- e2e2/test/cases/nvidia/mpi_test.go
This PR integrates multi-node NCCL testing into the tester package. The tester now accepts the following flags to configure the test:
- ncclTestImage: Specifies the base image to run the multi-node nccl test.
- efaEnabled: Determines whether to use the EFA in the cluster.
- nodeType: Specifies what type of nodes in the node groups will be used to run the multi-node NCCL test.
The tester can retrieve the hardware specifications from the nodes and render the nccl test manifest based on these specifications.
Testing
```
go test -v . -args -efaImage 665181186642.dkr.ecr.us-west-2.amazonaws.com/aws-k8s-tester/nccl-test:latest -skip-features single-node -efaEnabled=true
W0610 22:55:51.199584   28686 warnings.go:70] …
```
> Integrate multi-node nccl testing into the tester package

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/k8s.go
- kubetest2/internal/deployers/eksapi/metrics.go
This adds 2 new metrics for `Node` objects:
1. The number of seconds from EC2 instance launch time and the creation of the `Node` object.
2. The number of seconds from EC2 instance launch time and the `Node`'s `Ready` condition becoming true.
> Add node metrics for time to register, ready

- kubetest2/internal/deployers/eksapi/k8s.go
Fixes an issue in which the instance type label may be missing at the time of metric recording.
> Use instance type from EC2 API instead of Node label

- e2e2/test/cases/neuron/main_test.go
- e2e2/test/cases/neuron/neuron_test.go
- e2e2/test/cases/nvidia/main_test.go
- e2e2/test/cases/nvidia/mpi_test.go
- e2e2/test/cases/nvidia/unit_test.go
replace `wait.WithTimeout(timeout)` with `wait.WithContext(ctx))`
> replace `wait.WithTimeout(timeout)` with `wait.WithContext(ctx))`

- e2e2/internal/framework_extensions/client.go
- e2e2/test/cases/neuron/neuron_test.go
- e2e2/test/cases/nvidia/manifests/mpi-job-nccl-test-multi-node.yaml
- e2e2/test/cases/nvidia/mpi_test.go
- e2e2/test/cases/nvidia/unit_test.go
- e2e2/test/images/nvidia/gpu_unit_tests/tests/test_basic.sh
- e2e2/test/images/nvidia/gpu_unit_tests/tests/test_sysinfo.sh
- Pull the logs when test finished
- Remove unnecessary resources requests and limits in the nccl test manifest. And some instance type doesn't have `hugepages-2Mi`
Test:
```
go test -timeout 60m -v . -args -nvidiaTestImage public.ecr.aws/o5d5x8n6/weicongw:nvidia
2024/07/31 17:37:39 No node type specified. Using the node type p3.2xlarge in the node groups.
=== RUN   TestMPIJobPytorchTraining
=== RUN   TestMPIJobPytorchTraining/single-node
=== RUN   TestMPIJobPytorchTraining/single-node/MPIJob_succeeds
=== NAME  TestMPIJobPytorchTraining/single-node
mpi_test.go:71: Test log for pytorch-training-single-node:
mpi_test.go:72: Cloning into '/pytorch-examples'...
Note: switching to '0f0c9131ca5c79d1332dce1f4c06fe942fbdc665'.
You are in …
```
> Pull the logs when test finished and remove unnecessary resources requests and limits in the nccl test manifest

- .github/workflows/ci.yaml
- Dockerfile.kubetest2
- e2e2/internal/framework_extensions/client.go
- e2e2/test/cases/neuron/main_test.go
- e2e2/test/cases/neuron/neuron_test.go
- e2e2/test/cases/nvidia/main_test.go
- e2e2/test/cases/nvidia/manifests/mpi-job-pytorch-training-single-node.yaml
- e2e2/test/cases/nvidia/mpi_test.go
- e2e2/test/cases/nvidia/unit_test.go
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup.yaml.template
- The `GetJobLogs` was using the same context as the main context. This would cause if time out happens the tests will not print out the logs from the tests. Let the `GetJobLogs` use `context.Background()` to let it always prints out the logs.
- Add `e2e-neuron` test binary to the kubetest2 dockerfile.
- Set the default disk storage size to 100 GB
- Enforces the node group be in one AZ.
Test:
Tested it will always print out the logs even timeout reached 
```
go test -timeout 60m -v . -args -nvidiaTestImage public.ecr.aws/o5d5x8n6/weicongw:nvidia
2024/08/01 07:34:11 No node type specified. Using the node type p3.2xlarge in the node groups.
=== RUN   TestMPIJobPytorchTraining
=== RUN   TestMPIJobPytorchTraining/single-node
=== RUN …
```
> Fix GetJobLogs and e2e-neuron binary not exits issue.

- Dockerfile.kubetest2
Bump go version because 1.21 is no longer listed in the download list at https://go.dev/dl/?mode=json
> Bump go version in kubetest2 image

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
Adds a flag to control how long we wait for nodes to be launched. Some instance types are scarce and we may need to wait longer than the default (20 minutes).
> Add --node-creation-timeout flag

- e2e2/test/cases/nvidia/manifests/job-hpc-benchmarks.yaml
- e2e2/test/cases/nvidia/mpi_test.go
- e2e2/test/cases/nvidia/unit_test.go
- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
- Add hpc benckmark to unit test,
- Add the 'capacity-reservation' flag to the deployer. If this flag is enabled, it will automatically search for a capacity reservation in the account that matches the instance type and the number of available nodes. It will then create the unmanaged node group on this capacity reservation.
> Add hpc benckmark to unit test, and add "capacity-reservation" flag to deployer

- kubetest2/internal/deployers/eksapi/nodegroup.go
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
When testing EFA for bottlerocket, run into 
```
Warning  Evicted              29s   kubelet            The node was low on resource: ephemeral-storage. Threshold quantity: 2867269745, available: 1396568Ki.
```
As bottlerocket has 2 volume, we should use `/dev/xvdb` for data volume
> Fix volume capacity issue

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
The default instance type used by managed nodegroups is too small for our use case; this PR will pass our existing list of default instance types to the `eks:CreateNodegroup` API if `--instance-types` is not specified.
This also adds a default `AmiType` to the `eks:CreateNodegroup` response, since we can't pass instance types without aligning it with the architecture of the `AmiType`.
> Add default instance types for managed nodegroups

- kubetest2/internal/deployers/eksapi/nodegroup.go
remove `A` type ec2 instances from default list due to lack of support in isolated regions
> Remove unsupported instance types in isolated regions

- e2e2/test/cases/nvidia/main_test.go
Timeouts during `Setup` can be caused by a failure in one of:
1. mpi-operator
2. nvidia-device-plugin
3. efa-device-plugin
This adds some logging to narrow things down.
> Add debug logging for e2e-nvidia setup

- e2e2/test/cases/neuron/main_test.go
- e2e2/test/cases/nvidia/main_test.go
- kubetest2/internal/deployers/eksapi/nodegroup.go
- kubetest2/internal/deployers/eksapi/templates/templates.go
- kubetest2/internal/deployers/eksapi/templates/userdata_bottlerocket.toml.template
- kubetest2/internal/deployers/eksapi/userdata.go
- kubetest2/internal/deployers/eksapi/userdata_test.go
- Make this as flag to support test cases when the device plugin baked in to the AMI
- Remove `[settings.efa]` for BR config as we won't need it after https://github.com/bottlerocket-os/bottlerocket-core-kit/pull/141
> Opt in device plugin

- e2e2/test/images/nvidia/Dockerfile
- Ensure versions are aligned throughout (CUDA major and minor versions used, Ubuntu major version, etc.)
- Remove unused or unnecessary packages
- Update NCCL version from `2.18.5` to `2.22.3`
- Update aws-ofi-nccl version from `1.9.1` to `1.11.0`
- Use a pinned version for NCCL tests
- Use generated artifacts (zip archives) instead of git clones of repositories
> chore: Update GPU Dockerfile versions

- e2e2/test/cases/nvidia/manifests/job-unit-test-single-node.yaml
- e2e2/test/images/nvidia/Dockerfile
- e2e2/test/images/nvidia/gpu_unit_tests/tests/test_sysinfo.sh.data/g5.8xlarge/gpu_count.txt
- e2e2/test/images/nvidia/gpu_unit_tests/tests/test_sysinfo.sh.data/g5.8xlarge/numa_topo.txt
- e2e2/test/images/nvidia/gpu_unit_tests/tests/test_sysinfo.sh.data/g5.8xlarge/nvidia_persistence_status.txt
- e2e2/test/images/nvidia/gpu_unit_tests/tests/test_sysinfo.sh.data/g5.8xlarge/nvidia_smi_topo.txt
encountered several issue when execute unit test for bottlerocket 
1. 
```
common.sh: line 14: nvidia-smi: command not found
```
fix by adding resource limit
2.
dgcmi not found
fix by installing `datacenter-gpu-manager`
3. missing file for test-sysinfo, followed the readme to add expected files
```
k logs unit-test-job-nb6gn
ok - test_01_device_query
ok - test_02_vector_add
ok - test_03_bandwidth
ok - test_04_bus_grind
ok - test_05_dcgm_diagnostics
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:--  0:02:03 --:--:--     0
curl: (56) Recv failure: Connection reset by peer
% Total    % Received % Xferd  Average Speed …
```
> Fix unit test

- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
- Expose all 32 EFA interfaces on p5 launch template
> fix: Expose all 32 EFA interfaces on p5 launch template

- e2e2/test/cases/nvidia/main_test.go
- e2e2/test/cases/nvidia/manifests/job-unit-test-single-node.yaml
- e2e2/test/cases/nvidia/unit_test.go
- e2e2/test/images/nvidia/Dockerfile
- e2e2/test/images/nvidia/gpu_unit_tests/bash_unit
- e2e2/test/images/nvidia/gpu_unit_tests/unit_test
Issue 1:
Build failed in CodeBuild 
```
Step 17/26 : ARG NCCL_VERSION=2.22.3-1+cuda${CUDA_MAJOR_VERSION}.${CUDA_MINOR_VERSION}
---> Running in 1a06f4ac470e
Removing intermediate container 1a06f4ac470e
---> 07cde702fb9b
Step 18/26 : RUN apt update   && apt install -y     libnccl2=${NCCL_VERSION}      libnccl-dev=${NCCL_VERSION}
...
E: Version '2.22.3-1' for 'libnccl2' was not found
E: Version '2.22.3-1' for 'libnccl-dev' was not found
The command '/bin/sh -c apt update   && apt install -y     libnccl2=${NCCL_VERSION}      libnccl-dev=${NCCL_VERSION}' returned a non-zero code: 100
```
temp fix by hardcode it
Issue 2:
The unit test `test_nvidia_persistence_status` is failing on Bottlerocket as it is not enabled, there are an incoming release …
> Fix Nvidia Image build

- e2e2/test/images/nvidia/gpu_unit_tests/bash_unit
- e2e2/test/images/nvidia/gpu_unit_tests/tests/common.sh
> Fix get_instance_type

- e2e2/test/cases/nvidia/manifests/mpi-job-nccl-test-multi-node.yaml
- e2e2/test/images/nvidia/Dockerfile
MPI5 runinto below issue on AL2 & AL23
```
[multi-node-nccl-test-launcher:00001] PMIX ERROR: PMIX_ERR_BAD_PARAM in file gds_utils.c at line 308
[multi-node-nccl-test-launcher:00001] PMIX ERROR: PMIX_ERR_BAD_PARAM in file gds_hash.c at line 496
[multi-node-nccl-test-launcher:00001] PRTE ERROR: Bad parameter in file base/odls_base_default_fns.c at line 768
```
MPI4 is recommended https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl.html
> Config MPI4 for EFA

- kubetest2/go.mod
- kubetest2/go.sum
- kubetest2/internal/deployers/eksapi/aws.go
- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/k8s.go
- kubetest2/internal/deployers/eksapi/logs.go
- kubetest2/internal/deployers/eksapi/logs_ssm_doc.json
- kubetest2/internal/deployers/eksapi/templates/infra.yaml
This adds optional node log collection after the Up() and Down() phases of the deployer. If the `--log-bucket` flag is passed, an SSM document will be used to execute the `/etc/eks/log-collector/eks-log-collector.sh` script that is included in Amazon Linux based EKS AMIs. The resulting tarball is uploaded to the S3 bucket, with its key including the run ID + phase.
> Collect node logs after --up, --down phases

- kubetest2/internal/deployers/eksapi/k8s.go
This adds an `osDistro` dimension to the Node metrics, for `osImage` values that start with `Amazon Linux`.
For AL2, `osImage` is always `Amazon Linux 2`. But for AL2023, it's the release-specific `Amazon Linux 2023.6.20241010`. This PR adds an `osDistro` dimension that will be `Amazon Linux 2`, `Amazon Linux 2023`, `Amazon Linux 2025`, etc. to make aggregate cloudwatch queries easier.
> Add osDistro metric dimension

- kubetest2/internal/deployers/eksapi/cluster.go
- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/infra.go
N/A
Add support for existing cluster
Testing:
```
kubetest2 eksapi --up --down --static-cluster-name=static-kubetest2-cluster --node-role-arn arn:aws:iam::xxx:role/NodeRole \
--endpoint-url https://api.beta.us-west-2.wesley.amazonaws.com \
--user-data-format=bottlerocket --generate-ssh-key \
--emit-metrics --unmanaged-nodes --node-name-strategy=SessionName \
--ami=ami-0f788954ca6a52fba --kubernetes-version=1.29 --nodes=2 --instance-types=inf2.xlarge 
```
```
I1021 04:06:44.667431      14 app.go:61] The files in RunDir shall not be part of Artifacts
I1021 04:06:44.667520      14 app.go:62] pass rundir-in-artifacts flag True for RunDir to be part of Artifacts
I1021 04:06:44.667545      14 app.go:64] RunDir for this run: …
```
> Add support for static cluster

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/templates/busybox_deployment.yaml.template
- kubetest2/internal/deployers/eksapi/templates/templates.go
For static cluster, use dummy busybox to ensure the node to be ready before e2e test and teardown them after test
```
kubetest2 eksapi --up --down --static-cluster-name=129-static-cluster --test=multi -- --fail-fast=false -- ginkgo --use-binaries-from-path --parallel=6 --ginkgo-args='--no-color' --focus-regex='\[Conformance\]' --skip-regex='\[Serial\]|\[Disruptive\]|\[Slow\]|Garbage.collector'
...
Ran 347 of 7407 Specs in 792.495 seconds
SUCCESS! -- 347 Passed | 0 Failed | 0 Pending | 7060 Skipped
I1101 18:13:18.967304      76 deployer.go:392] Waiting for nodes to be removed: Current node count: 0
```
> Ensure node for static cluster

- kubetest2/internal/deployers/eksapi/templates/infra.yaml
By default this won't allow access, but can easily be hacked on to enable SSH for testing.
make the inbound security rule for SSH a no-op
> make the inbound security rule for SSH a no-op

- e2e2/test/cases/neuron/manifests/efa-device-plugin.yaml
- e2e2/test/cases/neuron/manifests/k8s-neuron-device-plugin.yml
- e2e2/test/cases/nvidia/manifests/efa-device-plugin.yaml
- e2e2/test/images/neuron/Dockerfile
- eks/neuron/neuron.go
- eks/trainium/trainium.go
* Add `trn2.48xlarge`
* Set workdir to /home/ubuntu in container image for neuron. Alleviates in issue where programs that try to write to the working directory are hit with irreconcilable permission denied errors due to the attempt to write to the root directory.
> Add trn2.48xlarge, set workdir to /home/ubuntu in neuron container image

- kubetest2/internal/deployers/eksapi/nodegroup.go
Leverage `EC2:DescribeInstanceTypes` API to dynamically scope down default instance types list to only those that exist in the test region.
Relies on error format:
```
operation error EC2: DescribeInstanceTypes, https response error StatusCode: 400, RequestID: <request_id>, api error InvalidInstanceType: The following supplied instance types do not exist: [<instance_type(s)>]
```
Specifically, the error handler relies on the presence of `InvalidInstanceType` in the error string, a printed list of the instance types being discoverable by indexing the last occurrence of a forward square bracket (`[`), and multiple types being separated by a comma and a space (`, `).
Tested this by appending `ec2types.InstanceTypeTrn1n32xlarge` to the defaultInstanceTypes_x86_64 …
> Dynamically filter out invalid instance types

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/janitor.go
- kubetest2/internal/deployers/eksapi/logs.go
- kubetest2/internal/deployers/eksapi/node.go
This refactors the `NodegroupManager` into a more general `NodeManager` that supports EKS Auto. A "placeholder" deployment will be created that makes the `--nodes` flag effective when `--auto-mode` is used.
There's a similar thing being done for `--static-cluster-name`. That will be removed in later PR's; I haven't touched that behavior so that CI jobs can be migrated without breakage.
> Create placeholder deployment for Auto clusters if --nodes > 0

- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
This PR enhances the unmanaged-nodegroup-efa.yaml CloudFormation template to support trn1.32xlarge instances with 8 EFA-enabled network interfaces. Key changes include:
* New Condition: Added IsTRN1Node to detect when InstanceType is trn1.32xlarge.
*  EFA Configuration: Configured 8 EFA interfaces for trn1.32xlarge under NodeLaunchTemplate.
* Backward Compatibility: Ensured P4 and P5 instance logic remains unchanged.
These changes enable EKS unmanaged node groups to leverage the full EFA capacity of trn1.32xlarge instances
> add(kubetest2/eksapi): Add EFA Support for trn1.32xlarge Instances

- e2e2/test/cases/neuron/main_test.go
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
This PR fixes a YAML syntax issue in the unmanaged-nodegroup-efa.yaml file. The issue was caused by an incorrect indentation and missing list marker for the !If conditional block. 
**Changes made:**
- Added the missing `-` to properly denote the start of the !If block list.
- Ensured proper alignment of the nested block under the !If condition for `IsTRN1Node`.
This fix resolves the "YAML not well-formed" CloudFormation validation error (line 464, column 13) encountered during stack creation with EFA-enabled unmanaged nodegroups.
> fix(kubetest2): Fix YAML syntax issue in unmanaged-nodegroup-efa.yaml for !If conditional block

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/node.go
Adds a flag, `--instance-type-archs` that can be used to choose default instance types for specific architecture(s).
> Add --instance-type-archs flag

- kubetest2/internal/deployers/eksapi/node.go
Normalizes the values of `--instance-type-archs` to handle `amd64` and `aarch64`, which do not directly map to `ec2types.ArchitectureValues`.
> Normalize --instance-type-archs values

- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
This PR addresses issues related to incorrect `DeviceIndex` and `NetworkCardIndex` assignments for EFA interfaces in the unmanaged nodegroup launch template. The incorrect configuration previously led to AWS errors indicating that the specified device index exceeded the maximum number of devices supported by the network card.
*Key Changes*
- **Primary Interface**: eth0 is now properly set with `DeviceIndex: 0` and `NetworkCardIndex: 0` for all node types.
- **EFA Interfaces**: All subsequent EFA interfaces are configured with `DeviceIndex: 1`, and `NetworkCardIndex` is incremented for each new EFA.
- **Instance Type Compatibility**: Ensured that the new configuration works for **P4**, **P5**, and **TRN1** instance types.
- …
> fix(kubetest2/eksapi): Fix DeviceIndex and NetworkCardIndex for EFA interfaces, ensure DeleteOnTermination is true

- kubetest2/internal/deployers/eksapi/node.go
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
* Fix the node group deletion failed caused by the ENI leakage for EFA security group. 
* The EFA Security group is created in the [unmanaged-nodegroup-efa.yaml](https://github.com/aws/aws-k8s-tester/blob/72ebc98f2d01f5ff539c6619a5082010e316e9bf/kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml#L67-L74) which is a customized security group specified in the node launch template, so it will be created and deleted during unmanaged nodegroup stack creation and deletion.
* The reason why our [old leaked eni clean up in infra.go](https://github.com/aws/aws-k8s-tester/blob/main/kubetest2/internal/deployers/eksapi/deployer.go#L335) doesn't work as expected is because we are using customized security group in node launch template instead of the …
> handle EFA security group eni leakage

- kubetest2/internal/deployers/eksapi/infra.go
The tag key we use to locate leaked ENIs prior to infrastructure stack deletion differs for ENIs created by the VPC CNI and the IPAM controller. This PR adds the tag key for the latter.
> Delete ENIs leaked by the IPAM controller

- e2e2/test/cases/nvidia-inference/main_test.go
* Nvidia Inference test randomly failed with error `Setup failure: no node has >= 1 GPU(s)`. It is because after apply NVIDIA device plugin it will take some time for the gpu info propagated to the node status. And if the checkGpuCapacity happened before propagation finished, it will failed
* To fix above issue, add retry for GPU capacity check
> Fix Setup failure: no node has >= 1 GPU(s) in Nvidia Inference test

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/janitor.go
- kubetest2/internal/deployers/eksapi/k8s.go
- kubetest2/internal/deployers/eksapi/node.go
This aims to address an issue where the cluster's security group is left behind if we wait for nodes to be deleted by `eks:DeleteCluster`. We'll delete our "placeholder deployment" and the `NodePool`, then wait for all `Node` objects to be deleted, prior to calling `eks:DeleteCluster`.
> Wait for deletion of auto mode nodes

- e2e2/test/cases/nvidia-inference/bert_inference_test.go
- e2e2/test/cases/nvidia-training/bert_training_test.go
- kubetest2/internal/deployers/eksapi/node.go
- kubetest2/internal/deployers/eksapi/templates/unmanaged-nodegroup-efa.yaml
* After I going through the control plane logs, I find the csr not approved and a bunch of unverified hosts. And this issue not always happened seems just flacky. I think we bump in this issue that EIP got attached around the same time when the certificate was published.  The issue is happening when customer attaches the EIP to the worker node to Eth0. As a result the public IP address of the node changes from 3.85.202.226 to 3.237.215.201. When API server tries to validate the address, it fails as it doesn't recognize the original public IP address of the node. When kubelet creates a secondary certificate request after 20mins, it succeeds as the new certificate contains EIP address to it. But out test is already finished this time.
* We see this is we use the …
> fix the security group issue

- kubetest2/internal/deployers/eksapi/deployer.go
- kubetest2/internal/deployers/eksapi/janitor.go
- kubetest2/internal/deployers/eksapi/node.go
Find below error when deleting unmanaged node group without AutoMode. Fix by only clean up these resources when it is AutoMode
```
January 06, 2025 at 15:02 (UTC-8:00)
Error: failed to delete node pool: no matches for kind "NodePool" in version "karpenter.sh/v1"
January 06, 2025 at 15:02 (UTC-8:00)
I0106 23:02:28.920402 12 node.go:289] placeholder deployment does not exist: kubetest2-eksapi-f0b52762-d024-466e-b8dd-08ba7cf96d3e
January 06, 2025 at 15:02 (UTC-8:00)
I0106 23:02:28.920421 12 node.go:218] deleting node pool...
January 06, 2025 at 15:02 (UTC-8:00)
I0106 23:02:28.205830 12 node.go:586] nodegroup does not exist: kubetest2-eksapi-f0b52762-d024-466e-b8dd-08ba7cf96d3e
January 06, 2025 at 15:02 (UTC-8:00)
I0106 23:02:28.205850 12 node.go:286] deleting …
```
> fix the node clean up failure without auto mode

- internal/deployers/eksapi/infra.go
Missing return caused unintentional error.
> Handle NoSuchEntity properly when sweeping instance profiles

- internal/deployers/eksapi/logs.go
When cluster creation fails, `k8sClient` is `nil`, causing a panic.
> Fix nil pointer when cluster creation fails

- .github/workflows/ci.yaml
- Dockerfile
This adds the `e2e` build tag for test compilation.
> Pass build tags for test executables

- Makefile
We need to install the upstream kubetest2 tools in addition to our own.
> Add upstream kubetest2 tools to artifacts

- cmd/kubetest2-eksapi-janitor/main.go
- internal/deployers/eksapi/infra.go
- internal/deployers/eksapi/janitor.go
This adds two features to the janitor:
1. Parallelism to sweep multiple resources at once. We spend a lot of time waiting, and when there's a big mess to clean up, this will come in handy. Controlled with the `--workers` flag. Default is 1.
2. A filter to target cleanup at stacks in a specific state. Default is all stacks (unchanged). Controlled by `--stack-status`.
3. Also adds a check for `nodeRoleName` to avoid errors when sweeping instance profiles.
> Add parallelism, stack status filter to janitor

- Makefile
`d7fcb799ce84ceda66c8b9b1ec8eefcbe226f293` -> `v0.0.0-20231113220322-d7fcb799ce84`
> Fix sigs.k8s.io/kubetest2 version ref

- internal/e2e/client.go
The check for `Kind` is not effective, we need to revert to the previous impl, but use the `MPIJobFacade`.
https://github.com/aws/aws-k8s-tester/blob/9bdcb4f19f9176f5e04cbbdb69c65274ea66294c/e2e2/internal/framework_extensions/client.go#L133-L140
> Fix job type check

- test/cases/neuron/manifests/k8s-neuron-device-plugin.yml
- test/images/neuron/Dockerfile
N/A
Update neuron unit test artifacts to Neuron SDK 2.21.0 to support trn2
Neuron docs: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/index.html#neuron-2-21-0-12-20-2024
Also some re-formatting.
Based on https://github.com/aws-neuron/deep-learning-containers/blob/main/docker/pytorch/training/2.5.1/Dockerfile.neuronx
> chore: update neuron unit tests to Neuron SDK 2.21.0

- .github/workflows/ci.yaml
Add the `neuron-training` image (`/home/mattcjo/github-aws-mattcjo/aws-k8s-tester/test/images/neuron-training/Dockerfile`) to the git workflow. 
> fix(test/neuron-training): Add neuron-training image to git workflow

- internal/e2e/mpioperator/types.go
- internal/e2e/mpioperator/types_test.go
Fixes an issue seen in the `nvidia` test cases:
```
mpi_test.go:71: multiple GroupVersionKinds associated with Go type *mpioperator.MPIJobFacade within the Scheme, this can happen when a type is registered for multiple GVKs at the same time: callers can either fix their type registration to only register it once, or specify the GroupVersionKind to use for object passed in; refusing to guess at one: ["kubeflow.org/v2beta1, Kind=MPIJob" "kubeflow.org/__internal, Kind=MPIJob"]
```
The `_internal` version this is referring to is necessary when decoding types with a scheme, but causes this error when the scheme is used to map types to API types in the framework's client.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
> fix: only register internal version of MPIJobFacade for unit tests

- go.mod
- go.sum
The cert for `go.opencensus.io` has been fixed, and this `replace` breaks our standard installation methond (`go install ...`).
> Remove replace directive for go.opencensus.io

- internal/deployers/eksapi/infra.go
- internal/deployers/eksapi/templates/infra.yaml
The cluster creation may fail due to the policy not exist in EKS Auto non-GA regions
The policy will be attached when the auto mode flag is true. and this flag should be controlled by clients in those regions GAed EKS Auto
Tests Done: 
build and tested in personal dev account for both auto-mode and non-auto-mode
> Attach EKS auto policies for Auto cluster only

- internal/e2e/logs.go
- test/cases/nvidia/containerd_test.go
- test/cases/nvidia/manifests/daemonset-containerd-check.yaml
*Issue #, if available:*  
Addresses the known bug in nvidia-container-toolkit `1.17.0` ([bug(nvidia-container-toolkit): incorrect containerd config #2041](https://github.com/awslabs/amazon-eks-ami/issues/2041)) which can drop EKS defaults on Amazon Linux 2 (AL2) AMIs.
*Description of changes:*  
- **Introduces a new containerd test** under `test/cases/nvidia`, verifying each node’s `/etc/containerd/config.toml` includes:
1. **ECR references** (`.ecr.`) for the sandbox image (avoid fallback to `registry.k8s.io`),
2. The **NVIDIA GPU runtime** (`nvidia-container-runtime`),
3. **Systemd** cgroup settings (`systemd_cgroup = true` or `SystemdCgroup = true`).
- **Deploys a DaemonSet** that mounts `/etc/containerd/config.toml` and runs inline grep checks. If any required line is missing, the …
> feat(test/nvidia): Add Containerd Test to NVIDIA Suite for ECR and Systemd Validation

- internal/e2e/conditions.go
- test/cases/neuron-training/bert_training_test.go
- test/cases/neuron-training/main_test.go
- test/cases/neuron-training/manifests/bert-training.yaml
- test/cases/neuron-training/vars.go
- test/images/neuron-training/train.py
Neuron training seems to have a NCCL timeout at the first step mark for the first epoch on the very first run on a node, i.e., when the image has to pull. This gets around that by retrying it, since on the retry the image would already be present. The most obvious solution would be using some sort of barrier (e.g. xm.rendezvous() or dist.barrier()) before the first mark step, but those do not seem to accomplish the desired behavior.
> Stabilize neuron training test

- internal/deployers/eksapi/node.go
When using a managed nodegroup you will see something like the following if you provide `--instance-types` that end up getting filtered out by `nodeManager.getValidInstanceTypes`:
```
node.go:736] Eliminating instance type g3.4xlarge as an option
node.go:149] using instance types: []
```
in this scenario i expect that the kubetest2 deployer will abort due to being unable to launch any of my desired instance types, but instead it launches instances using the defaults. (ex. `t3.medium`)
> fix: error when none of the provided instance types are valid

- internal/deployers/eksapi/cluster.go
If the cluster waiter has never received a response from `eks:DescribeCluster` (for whatever reason) then `out` may be `nil`.
> fix: nil pointer when cluster creation fails

- internal/deployers/eksapi/cluster.go
- internal/deployers/eksapi/deployer.go
- internal/deployers/eksapi/janitor.go
Makes the cluster creation timeout configurable; default remains 15 minutes.
> feat: add --cluster-creation-timeout flag

- test/images/nvidia/Dockerfile
a new tag `v12.8` was released for https://github.com/NVIDIA/cuda-samples.git that changes the build system and several other features. 
This PR pins this repository to the tag it was originally built with.
> build(nvidia): pin cuda-samples version

- internal/e2e/resources.go
- test/cases/neuron/main_test.go
- test/cases/neuron/manifests/k8s-neuron-device-plugin.yml
- test/cases/neuron/manifests/multi-node-test-neuron.yaml
- test/cases/neuron/neuron_test.go
- test/cases/nvidia/main_test.go
- test/images/neuron/Dockerfile
Some changes so this test can support >2 nodes, and avoid flakes caused by early reads of neuron device information from the node before values are set.
Ran on 4 trn1.32xlarge nodes:
```
$ go test ./... -v -tags=e2e -timeout=60m --test.run=^TestNeuronNodes$/multi-node --efaEnabled=true --neuronTestImage=<IMAGE_URI> --nodeType=trn1.32xlarge 
$ k get pods
NAME                                   READY   STATUS    RESTARTS        AGE
multi-node-nccom-test-launcher-2z5lz   1/1     Running   2 (3m33s ago)   3m36s
multi-node-nccom-test-worker-0         1/1     Running   0               3m36s
multi-node-nccom-test-worker-1         1/1     Running   0               3m36s
multi-node-nccom-test-worker-2         1/1     Running   0               3m36s …
```
> fix(neuron/multi-node): Wait for neuron device info to propagate, enable run on more than 2 nodes

- test/cases/neuron-inference/bert_inference_test.go
- test/cases/nvidia-inference/bert_inference_test.go
- test/cases/nvidia-training/bert_training_test.go
* Add the job logs print for nvidia training, nvidia inference, neuron inference when the test failed which is easier for us to debugging the issue
* We already have the job log print for neuron training when it failed https://github.com/aws/aws-k8s-tester/blob/ecc47a9911a50e907dc0d5c065049cf89a067ce4/test/cases/neuron-training/bert_training_test.go#L102-L109
> print job logs when the job failed for debugging

- test/cases/quick/io_uring_test.go
- test/cases/quick/main_test.go
https://github.com/awslabs/amazon-eks-ami/issues/2070
This PR adds an e2e test to detect io_uring-related hangs that can occur when running npm install with CPU limits. The test:
- Logs cluster node information including kernel versions
- Creates a pod with CPU limits (500m) that attempts to install webpack
- Fails if the installation hangs for more than 10 minutes
- Passes if the installation completes successfully
This test would have caught the issue reported in #2070 where npm installations would hang indefinitely on certain AMIs (kernel 6.1.115-126.197.amzn2023) due to an io_uring kernel bug. The test uses the ECR-hosted Ubuntu noble image and webpack as a representative large npm package to trigger potential io_uring issues. …
> feat(test/quick): Add test to detect io_uring hangs with npm install 

- .github/workflows/ci.yaml
- internal/deployers/eksapi/node.go
- internal/deployers/eksapi/templates/templates.go
fixes test error:
```
--- FAIL: Test_UnmanagedNodegroup (0.00s)
templates_test.go:19: template: unmanagedNodegroup:129:14: executing "unmanagedNodegroup" at <.NetworkInterfaces>: can't evaluate field NetworkInterfaces in type templates.UnmanagedNodegroupTemplateData
```
due to the template not being used in the kubetest2 deployer code path in favor of an inline struct type. this PR adds the `NetworkInterfaces` field to the template definitions and updates the usages in the deployer.
also adds a `go test ./...` call to the build workflow.
> fix(templates): refactor template to have network interface

- internal/deployers/eksapi/infra.go
Fixes an issue when no instance types are specified on the command-line. Default instance types are currently resolved after the infrastructure stack is created.
> fix: handle empty instance type list for AZ resolution

- internal/deployers/eksapi/infra.go
We recently inadvertently added validation that all request instance types can be ran in the created VPC - which can be too strict when trying to run scarce instance types. 
All the requested instance types are added to an ASG which scales based on availability of the instance types - therefore we shouldn't directly validate that all the instance types can be ran in all the AZs, just that we're selecting the AZs where most instance types can be ran so that the ASG has the best change at scaling. This is particularly important for GPU instance types, where it might be preferable to pass a long list of instance types which may have zero overlap.
This also addresses the edge case of the requested instance type(s) only being offered in a …
> fix: best effort AZ selection for infra stack

- hack/download-kubernetes-binaries.sh
for newer binaries that have not been added to `https://storage.googleapis.com/kubernetes-release/release`, we'll fallback to `https://storage.googleapis.com/k8s-release-dev/ci
` bucket.
*Testing:*
```bash
> hack/download-kubernetes-binaries.sh "1.33" "linux" "amd64"
Release marker: latest-1.33.txt
Kubernetes version: <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/latest-1.33.txt</Details></Error>
Downloading bundle: kubernetes-client
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: …
```
> build: fallback to release ci dev for kuberentes binaries

- hack/download-kubernetes-binaries.sh
this was a fix that should have gone with https://github.com/aws/aws-k8s-tester/pull/602.
fix fallback mechanism, non-zero return codes were not bubbled up from inner routine.
the [workflow from the previous PR](https://github.com/aws/aws-k8s-tester/actions/runs/14365987157/job/40278912677?pr=602#step:3:13364) ended up showing some incorrect behavior that passed, so the signal was lost
```
#19 [stage-1  9/14] RUN ./download-kubernetes-binaries.sh "latest" "linux" "amd64"
#19 0.132 Release marker: latest.txt
#19 0.310 Kubernetes version: v1.32.0-alpha.0
#19 0.311 Downloading bundle: kubernetes-client
#19 1.730 Downloading bundle: kubernetes-test
#19 5.908 binary download failed from release bucket, falling back to ci dev release
#19 6.074 …
```
> fix: return nonzero inside download binary func

- internal/deployers/eksapi/node.go
`t3.large` is a highly available instance type, so this helps ensure test capacity.
> Add t3.large to eksapi default x86-64 instance types

- internal/deployers/eksapi/templates/userdata_bottlerocket.toml.template
- internal/deployers/eksapi/userdata_test.go
- test/cases/neuron/manifests/multi-node-test-neuron.yaml
- test/cases/neuron/manifests/single-node-test-neuronx.yaml
- test/images/neuron/Dockerfile
More context in #561, enables testing a bottlerocket feature to specify the userID and groupID ownership of neuron devices. It also more generally runs both containers as non-root, except the worker container still needs to be able to run sshd as root, ref https://www.ssh.com/academy/ssh/sshd.
> feat(neuron): run multi-node-nccom-test as non-root

- internal/deployers/eksapi/node.go
- internal/deployers/eksapi/templates/templates.go
- internal/deployers/eksapi/templates/userdata_nodeadm.yaml.mimepart.template
- internal/deployers/eksapi/userdata.go
- internal/deployers/eksapi/userdata_test.go
add kubelet featureGate to `NodeConfig` if the kubernetes version is 1.33 which applies only to AL2023 nodes created by the `eksapi` deployer.
> feat(al2023): enable DRA in kubelet for 1.33

- test/images/nvidia-training/Dockerfile
fixing a crumb from https://github.com/aws/aws-k8s-tester/pull/612
> fix: nvidia training image build

- test/cases/nvidia/manifests/job-hpc-benchmarks.yaml
We run this job with mpirun creating 1 process for each GPU. I really don't see why we would want 20 completions here, and functionally that takes a bit over an hour to complete - which means runs of this are likely to just timeout since most users would apply a 60 minute or less timeout. 
> fix(nvidia/hpc-benchmarks): run job with 1 completion

- test/cases/neuron-inference/main_test.go
* neuron inference test failed with no Neuron capacity found. Neuron training and nccom could pass the validate which add the wait time, could just latency issue. [reuse the AllNodesHaveNonZeroResourceCapacity helpful function with wait time to check the neuron capacity ready same as neuron training test](https://github.com/aws/aws-k8s-tester/blob/main/test/cases/neuron-training/main_test.go#L185-L206)
```
2025/05/16 08:20:14 [INFO] Discovering cluster's Neuron capacity...
2025/05/16 08:20:14 [WARN] Node ip-192-168-164-46.us-west-2.compute.internal (type=inf2.48xlarge) lacks 'aws.amazon.com/neuron'.
2025/05/16 08:20:14 [WARN] Node ip-192-168-164-46.us-west-2.compute.internal (type=inf2.48xlarge) lacks 'aws.amazon.com/neuroncore'.
2025/05/16 08:20:14 [INFO] …
```
> add wait time to check neuron capacity ready

- Makefile
This could cause tests directly calling `--flake-attempts` as a tester arg to fail, or any other flags that might have been removed in the diff.
The main benefit this change gets is shifting to test package info store in https://dl.k8s.io rather than the bucket
https://github.com/kubernetes-sigs/kubetest2/commit/7dee8a65e642615a9b753455f5b3c23dd3411a3d
> feat: install latest kubetest2

- .github/workflows/ci.yaml
- internal/e2e/ec2.go
- test/cases/efa/commons.go
- test/cases/efa/main_test.go
- test/cases/efa/pingpong_test.go
- test/cases/efa/unit_test.go
- test/images/efa/Dockerfile
- test/images/efa/scripts/unit-test.sh
Adds some initial tests to validate just EFA capacity. This is useful to run as a pre-flight check before running neuron or nvidia test cases that may use or require EFA, but also for testing EFA directly and on instance types which support it but don't have accelerators.
These are mainly intended as smoke tests at the moment, but sets up for more advanced future testing. At the moment, this will:
1. Verify that the EFA device capacity on the nodes is consistent with the expected.
2. Verify that all the requested number of EFA devices are visible within the container.
3. Verify that RDM and DGRAM endpoints are available for each EFA device.
4. Verify that two different pods can ping pong traffic between each other via efa (using the …
> feat: add tests to validate EFA

- test/images/nvidia-training/Dockerfile
N/A
1. Re-declared `CUDA_MAJOR_VERSION `and `CUDA_MINOR_VERSION` to fix the below error during build
```
3.702 E: Version '2.26.2-1+cuda.' for 'libnccl2' was not found
3.702 E: Version '2.26.2-1+cuda.' for 'libnccl-dev' was not found 
``` 
2. Removed trailing backslash at the end of the NCCL installation command
> Fixed Dockerfile for NCCL installation

- test/cases/nvidia-training/main_test.go
- test/manifests/assets/dcgm-exporter.yaml
- test/manifests/raw.go
This PR is to add DCGM Exporter to the test environment for eventual CloudWatch integration to view GPU metrics. Changes involve: Added DCGM Exporter DaemonSet in the default namespace, []byte array declared in `raw.go` and applied manifest + supporting function in `main_test.go`. 
On running `./nvidia-training.test` we can view the dcgm pods running before clean up:                                            
```
>> kubectl get pods -n default -l app.kubernetes.io/name=dcgm-exporter
NAME                  READY   STATUS    RESTARTS   AGE
dcgm-exporter-7575j   1/1     Running   0          8m1s
dcgm-exporter-jjv7r   1/1     Running   0          8m1s
dcgm-exporter-lcqtq   1/1     Running   0          8m1s
dcgm-exporter-nzd44   1/1 …
```
> DCGM Exporter Setup

- internal/deployers/eksapi/deployer.go
- internal/deployers/eksapi/infra.go
For `Error: failed to wait for infrastructure stack creation: waiter state transitioned to Failure` on creating cluster due to IPv6 CIDR not being supported in local AZs.
*Description of changes:*. 
Added filtering in `DescribeAvailabilityZones` to only request regular availability zones (`zone-type=availability-zone`). Modified `counts` to consider regular AZs only.
> Filter out local zones when selecting AZs in infra.go

- .github/workflows/ci.yaml
One of the nvidia image builds fails due to running out of disk space. there is space that can be reclaimed, so we're attempting to do that before initializing the docker build.
> ci: free up disk space before build

- test/images/nvidia-training/Dockerfile
- test/images/nvidia/Dockerfile
This PR updates nvidia test images to build NCCL using the cuda version that ships with the container, rather than trying to match with the correct package from upstream repository (apt in this case).
> feat(nvidia): build nccl from source

- test/cases/nvidia/manifests/mpi-job-nccl-test-multi-node.yaml
This static `NCCL_P2P_NET_CHUNKSIZE` value was causing failure in `alltoall` nccl-test perfs, and removing them fixed the issue.
Would see issues like the following if the value was incorrectly set:
```
[1,0]<stdout>:multi-node-nccl-test-worker-0: Test NCCL failure alltoall.cu:62 'unhandled cuda error (run with NCCL_DEBUG=INFO for details) / '
[1,3]<stdout>:[2025-07-01 22:28:44] multi-node-nccl-test-worker-0:26:54 [3] proxy.cc:1665 NCCL WARN [Service thread] Error encountered progressing operation=Connect, res=3, closing connection
```
May need more investigation, or just not a value that should be statically optimized.
> fix(nvidia): remove chunksize conflicting with alltoall perf

- internal/deployers/eksctl/deployer.go
- internal/deployers/eksctl/down.go
[#595 ](https://github.com/aws/aws-k8s-tester/issues/595)
This PR adds the capability to **delete** EKS nodegroups using the --down flag. The changes include:
- Added a new SkipDrain flag option to control node draining behavior during deletion
- The nodegroup deletion supports an optional --drain=false flag to skip draining nodes before deletion
- Enhanced the Down() function to support two deployment targets:
- nodegroup: Deletes a specific nodegroup from a cluster
- cluster: Deletes the entire EKS cluster (existing behavior)
- Added proper error handling and logging for both nodegroup and cluster deletion operations
Tests Done
```
kubetest2 eksctl \
--cluster-name=my-cluster-130 \
--nodegroup-name=aarch64-aws-k8s-130 \ …
```
> feat(deployer/eksctl): allow deleting nodegroupds with --down, skip draining nodegroups option

- test/cases/nvidia/manifests/mpi-job-nccl-test-multi-node.yaml
- test/cases/nvidia/mpi_test.go
This PR increases coverage of different perf nccl-tests. adding all 3 of `all_reduce`, `all_gather`, and `alltoall` in the same multi-node test.
It also ensures that logs are printed from the job even when the job has not completed by a new, upfront deadline of 10 minutes (tunable in the future) and prints the job logs even on failure.
> feat(nvidia): run multiple multi-node perfs

- test/cases/neuron/main_test.go
- test/cases/neuron/neuron_test.go
- test/cases/nvidia/mpi_test.go
- test/manifests/raw.go
This PR changes several `t.Fatal` calls to `t.Error` so that teardown does not partially execute. it also makes the `main_test.go` context cancellable via `SIGINT`.
> fix: ensure neuron test teardown completes

- test/cases/nvidia/mpi_test.go
This PR adds logging for the mpi job spec and status after the run either succeeds or fails.
also avoids partially completing teardown.
> chore(nvidia): provide more test job info

- test/cases/efa/commons.go
- test/cases/efa/main_test.go
- test/images/efa/Dockerfile
- test/images/efa/scripts/unit-test.sh
The EFA installer comes with a utility to validate the installation by ping ponging traffic over EFA on localhost. This adds a step to run that in the unit test.
Sample test output:
```
=== RUN   TestPingPong
=== RUN   TestPingPong/pingpong
pingpong_test.go:155: need at least 2 nodes with EFA capacity, got 1
--- FAIL: TestPingPong (0.07s)
--- FAIL: TestPingPong/pingpong (0.07s)
=== RUN   TestUnit
=== RUN   TestUnit/unit
=== RUN   TestUnit/unit/Unit_test_succeeds
=== NAME  TestUnit/unit
unit_test.go:132: Logs for pod "efa-unit-0"
Running test on a g5.24xlarge
provider: efa
fabric: efa-direct
domain: rdmap0s26-rdm
version: 201.0
type: FI_EP_RDM
protocol: FI_PROTO_EFA
provider: efa
fabric: efa
domain: rdmap0s26-rdm
version: 201.0
type: …
```
> feat(efa): add validation for EFA on single node

- internal/deployers/eksapi/deployer.go
Switch the CW infrastructure related components to deploy if user opts in.
> feat(eksapi): optionally deploy CW infra

- internal/deployers/eksapi/infra.go
Change CloudWatch stack name from `'cloudwatch-{UUID}' `to `'kubetest2-eksapi-{UUID}-cw'` so janitor can find and clean it up
> Renaming CloudWatch Stack Name

- test/cases/nvidia-training/main_test.go
Small change from preemptively rendering CloudWatch manifest to only Render CloudWatch Manifest if `metricDimensions ` was populated.
> fix: Render CloudWatch Manifest Placement

- Dockerfile
- test/cases/efa/main_test.go
bump the go version download to `go1.25` since 1.25 has been released and 1.23 was kicked off of hosting.
> chore: update Dockerfile go version to 1.25

- test/images/nvidia/gpu_unit_tests/unit_test
The failures in the unit test are not being bubbled up from the entrypoint without `errexit`
> fix(nvidia): make nvidia unit tests bubble error

- test/cases/nvidia/mpi_test.go
downstream CI sometimes fails to meet 5 minutes default timeout depending on network conditions.
this PR bumps it to 10 minutes.
> fix(nvidia): set longer timeout for single node pytorch test

- internal/e2e/conditions.go
- test/cases/disruptive/graceful_reboot_test.go
Adds a new test case that reboots the instance, intended to help sanity check that reboots are graceful. It's quite difficult from AWS APIs alone to determine the status of an instance after reboot (the `RebootInstance` API itself is asynchronous, EC2 status checks and SSM agent connectivity status are reconciled sparsely so they some times miss state changes). Ultimately, something must be executed on the node to determine whether or not it's running, this uses a pod to do so to keep it more as Kubernetes-oriented as possible. 
The test is based on the assumption that the pod `Exec` require kubelet responsiveness, and therefore a `143` to a command execution within a pod will decisively indicate that the node is shutting down. This is a …
> feat: add disruptive reboot test case

- test/cases/disruptive/graceful_reboot_test.go
Some improvements on top of https://github.com/aws/aws-k8s-tester/pull/692
Switches to directly using kubelet `/healthz` requests instead of pod exec being killed with a 143 for gauging that the instance has started shutting down. This brings more determinism in two ways:
1.  a pod can exit with a 143 for various unrelated reasons, but checking a connection refused from kubelet confirms kubelet has stopped listening on it's serving port and was therefore most probably killed
2. since the pod could also be killed well before kubelet, directly checking that kubelet is unresponsive makes sure that the second pod cannot be created until a new boot is complete. In the prior version, pods were sometimes left in `ContainerCreating` while the …
> fix: make reboot test more deterministic

- internal/e2e/health.go
- test/cases/disruptive/graceful_reboot_test.go
After running this test a few more times, I saw some cases where a different error would be returned by the kubelet health check and lead to an unnecessary failure. I was mainly seeing this with `connection reset by peer`, which presumably happened if kubelet was killed in the middle of the `/healthz` check, but I also added in the error `client connection lost` which should cover the same.
> fix: support more connection errors in reboot test
